### ISSUE TITLE
`edgedb server install` ignores the `revision` field in .jsonindexes

### ISSUE THREAD

**Issue by ambv** [edgedb/edgedb-cli#100]
- EdgeDB Version: 1.0a4
- EdgeDB CLI Version: 1.0a4
- OS Version: macOS 10.15

`edgedb server install` ignores the `revision` field in the .jsonindexes file, causing it to choose an outdated 1.0a4 build instead of the newest one.

Attached jsonindexes demonstrate the issue: [jsonindexes.zip](https://github.com/edgedb/edgedb-cli/files/4933602/jsonindexes.zip)

I'm interested in solving this with Paul's help.

**Comment by 1st1** [comment]
Any chance we can sort this out before Paul leaves on vacation?

**Comment by tailhook** [comment]
I think this is only an issue when we're making a release and doing multiple releases at the same day. So it doesn't look like an urgent issue.

**Comment by tailhook** [comment]
Or do we keep version the same (i.e. changing only revision) when we cut a patch release on alpha4?

**Comment by elprans** [comment]
Yes. Release builds of alphas differ only in the revision field. This situation might also arise when the bug is in the _packaging_ and not the source, so we re-roll the build of the same version, but with a newer revision.

**Comment by tailhook** [comment]
Well, I've expected something like `1a4.1`, but let me see what can be done now.

**Comment by tailhook** [comment]
Well, does it install the wrong version, or just prints the wrong revision when installing? I think it installs with `apt-get install edgedb-server-1-alpha4` without specifying revision.

**Comment by elprans** [comment]
On macOS it installed the wrong version.
