### ISSUE TITLE
Unable to change installation path

### ISSUE THREAD

**Issue by Kein** [edgedb/edgedb-cli#1003]
- EdgeDB CLI Version: 2.3.1 / Windows 10

I consider this a **bug**, not a FR. Edgedb-cli does not offer a way/allow to specify installation path, the customization options only have a single entry - `modify path variable [yes/no]`.  

Why is it so imperative an critical to install to `%APPDATA%\edgedb\bin`? You already modify path so the binaries can be searchable, so why does it matter where it is being installed? Why do I, as a user, have to [potentially] resort  to symlinks?

**Comment by tailhook** [comment]
Off the top of my head:

1. Make `edgedb cli upgrade` work, that location has to be known or configured somewhere known.
2. Also to avoid conflicts when someone put it into one location and then into another and then it depends on `PATH` which one is run and depends on some other thing which one is upgraded.

Do you mind providing some details, on why you need to change the location?

**Comment by tailhook** [comment]
I'm going to close this for now. You can always put the binary in any other place and it will work fine. But for how I don't feel that managing different installation path in the CLI itself is important.
