### ISSUE TITLE
Give a hint when users specify a version without `=`, `~`, or `^`

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#1051]
When users specify a version without using a range indicator (`=`, `~`, or `^`), their intention may be to set the range to `=<version>` rather than `^<version>`. In the output of the command, explain how their input was interpreted and demonstrate how to specify an exact version with `=` so they can try again if that was their intention.

Apply this across any commands that allow for a version to be specified:
- `edgedb project init --server-version`
- `edgedb project upgrade --to-version`
- `edgedb instance create --version`
- `edgedb instance upgrade --to-version`
- and any others I might have missed

**Comment by raddevon** [comment]
How do you feel about this, @scotttrinh? @msullivan?

**Comment by msullivan** [comment]
I think this is a good approach
