### ISSUE TITLE
Connects to the TCP endpoint instead of Unix socket when `--admin` is specified

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#1057]
When running the deployment guide for bare metal, the user gets stuck at setting the new password because the CLI throws a `PasswordRequired` error. This apparently happens because the CLI is not connecting via socket and is instead using TCP which requires the password.

- EdgeDB Version: 2.15 (I assume; unsure how to run version query because of the bug)
- EdgeDB CLI Version: 3.1.0+7faa31e
- OS Version: Ubuntu 22

Steps to Reproduce:

1. Follow the bare metal deployment guide for Ubuntu (and probably others)
2. Observe `PasswordRequired` error at password step

**Comment by tailhook** [comment]
The temporary workaround is add `--unix-path ./path/to/dir` where directory is `--runstate-dir` of the server (or `--data-dir` if runstate is not specified)

**Comment by tailhook** [comment]
We'll investigate this a little bit more, but from what it looks like now, `--unix-path` is not a workaround. It has to be required for `--admin`, it's just that error reporting is wrong here.
