### ISSUE TITLE
EdgeDB dump restore in Docker environment not documented (two possible methods not working)

### ISSUE THREAD

**Issue by falkfrentzen** [edgedb/edgedb-cli#1067]
- EdgeDB Version: on Mac: 2.16; Docker: v2 (latest on 2nd June 2023)
- EdgeDB CLI Version: 3.1.1
- OS Version: MacOS 13.0 (ARM64)

Steps to Reproduce:

1. version: "3" services: edgedb: image: edgedb/edgedb environment: EDGEDB_SERVER_SECURITY: insecure_dev_mode volumes: - "./dbschema:/dbschema" ports: - "5656:5656" 
2. docker-compose up -d

I recently opened issue #1063 https://github.com/edgedb/edgedb-cli/issues/1063 , which was quickly answered (thanks for the quick reply!). The reason I wanted to link and manually stop the docker instance was, that I thought it was a way to restore running docker database from a local dump. 

There are two ways I tried to achieve this: 
1. inside the docker container (freshly spun up without data, but with dbschema): 
- I mounted a directory "dumps" which holds a dump, to be restored
-> I tried the command "edgedb restore path", which yielded "no `edgedb.toml` found and no connection options are specified"
-> so I mounted my project's edgedb.toml and ran the command again, which yielded "project is not initialized and no connection options are specified"
-> therefore I ran the command "edgedb project init", which ran successfully, after switching the user from root to edgedb "su edgedb". However, running "edgedb instance list" afterwards, shows that the newly initialized instance is running on port 10700 and not on port 5656. Executing the command "edgedb restore path" now works, but it seems to restore the instance on port 10700 and not on 5656.

2. locally in Mac Terminal:
- I tried linking the docker instance to a local instance via the command "edgedb instance link my_instance" to then try and restore the dump from there. This didn't work, as I got the result "cannot restore: the database is not empty" -> I therefore tried stopping the instance, as specified in issue #1063 .

Is there a way to do this? I could not find any documenation on restoring edgedb in docker from a dump. 

Thanks in advance!

**Comment by elprans** [comment]
`edgedb project` and Docker are mostly orthogonal approaches to running EdgeDB in development.  When you run EdgeDB in a docker container it's more like a "remote" instance, so you need to tell the CLI how to connect to it explicitly, e.g. in your case specifying the port would likely be enough:

```
edgedb restore --password -P 5656 /path/to/dump
```

Alternatively, if you'd rather prefer to use the recommended approach of using bare `edgedb` and `createClient()` calls with your project, you can create an instance link to the Docker container as documented [here](https://www.edgedb.com/docs/intro/projects#using-remote-instances).

**Comment by elprans** [comment]
> "cannot restore: the database is not empty"

Sorry, missed this bit.  You cannot restore a dump to a non-empty instance.  Either make sure you're initializing a pristine instance (by mounting a new data directory or volume), or wipe the instance before restoring with `edgedb database wipe`

**Comment by falkfrentzen** [comment]
`edgedb database wipe` seems to be supported in versions >=3.0. The equivalent to this in v2 apparently is `edgedb database drop edgedb && edgedb database create edgedb`. Executing `edgedb database drop -I my_instance edgedb` results in the error "cannot drop the currently open database 'edgedb'". Is there any way around this or is the only way to achieve this with v2 by initializing a clean instance?

**Comment by elprans** [comment]
You cannot drop a database you're currently connected to, so a workaround is to create a temporary database, connect to it, drop/create `edgedb`, e.g:

```
edgedb> create database temp;
OK: CREATE DATABASE
edgedb> \c temp
temp> drop database edgedb;
OK: DROP DATABASE
temp> create database edgedb;
OK: CREATE DATABASE
temp> \c edgedb
edgedb> drop database temp;
OK: DROP DATABASE
```

**Comment by falkfrentzen** [comment]
Thanks a lot!

For anyone running into this problem in the future, I put together these commands, that worked for me: 

## edgedb v2: 
`edgedb instance link docker_instance -H localhost -P 5656 -d edgedb -u edgedb --tls-security insecure --trust-tls-cert --overwrite`

`edgedb query "create database tmp" -I docker_instance`

`edgedb instance destroy -I docker_instance --force`

`edgedb instance link tmp_instance -H localhost -P 5656 -d tmp -u edgedb --tls-security insecure --trust-tls-cert --overwrite`

`edgedb query "drop database edgedb" "create database edgedb" -I tmp_instance`

`edgedb instance destroy -I tmp_instance --force`

`edgedb instance link docker_instance -H localhost -P 5656 -d edgedb -u edgedb --tls-security insecure --trust-tls-cert --overwrite`

`edgedb query "drop database tmp" -I docker_instance`

`edgedb restore ./dumps/dump -I docker_instance`

`edgedb instance destroy -I docker_instance`

## edgedb v3: 
`edgedb instance link docker_instance -H localhost -P 5656 -d edgedb -u edgedb --tls-security insecure --trust-tls-cert --overwrite`

`edgedb database wipe -I docker_instance`

`edgedb restore ./dumps/dump -I docker_instance`

`edgedb instance destroy -I docker_instance`
