### ISSUE TITLE
Add support for Mint to edgedb install

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#109]
We can also support other popular debian derivatives

**Comment by 1st1** [comment]
See https://github.com/edgedb/edgedb/discussions/1565#discussioncomment-41327 for details

**Comment by tailhook** [comment]
For now we decided that we will not add support for this distribution. Everyone encouraged to use `edgedb server install --method=docker` on distributions we don't support directly. We will consider adding more distributions later when we had a bigger team.
