### ISSUE TITLE
Choosing "Customize Installation" gets stuck at (Y, n) prompt

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb-cli#110]
- EdgeDB Version: Alpha 4
- OS Version: Ubuntu 20 (mate),

Steps to Reproduce:

1. run edgedb-cli based installation
2. choose 2) customize installation

It then asks if it should modify the path, but no matter what key I press, it won't proceed.

> Modify PATH variable? (Y/n)
> Invalid choice "Y". Use single letter `y` or `n`.

**Comment by tailhook** [comment]
Fixed in master. We still need to release a CLI to make that work for curl/bash workflow.
