### ISSUE TITLE
Support installing nightly builds via edgedb-cli

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb-cli#114]
Nightly often contains important fixes (e.g. for recently reported bugs). Being able to test those without learning how to compile EdgeDB would be convenient.

**Comment by tailhook** [comment]
You can run `edgedb server install --nightly`

**Comment by CodesInChaos** [comment]
That complains that alpha-4 is already installed

**Comment by elprans** [comment]
That must be because nightlies still think they're pre-alpha4 (edgedb/edgedb#1597)

**Comment by tailhook** [comment]
I think it's probably because we wanted to have install to install single version and `upgrade --to-nightly` to install nightly and switch to that. But I'm somehow messed up with installing nightly and stable side by side. (I.e. `install --nightly` works only on a clean system). Will look into it.
