### ISSUE TITLE
Support for separate files as modules

### ISSUE THREAD

**Issue by Gobot1234** [edgedb/edgedb-cli#1148]
I'd really like to have support for some sort of import system which would allow for separate files as modules. The current way of throwing everything in one big default schema file can become hard to manage. This is somewhat alleviated by having collapsable sections in the schema.

I'm not fixed to any importing word (import/using/probably anything else you come up with are all fine)
```
# default.esdl
using user;  # imports the file as if it were defined inside a module block

# e.g.
type Blog {
    author: user::User;
}
```

In the meantime @raddevon suggested writing a script generate this all for me which I'll just share.
```ts
import { open, opendir } from 'node:fs/promises';

const HEADER = `# This file is @generated. DO NOT EDIT MANUALLY.\n`;

async function generateFile() {
  const DEFAULT_FILE = await open(`${__dirname}/default.esdl`, 'w+');
  await DEFAULT_FILE.writeFile(HEADER);

  for await (let file of await opendir(__dirname)) {
    if (!file.isFile() || !file.name.endsWith('.esdl')) continue;

    let f = await open(`${file.path}/${file.name}`, 'r');
    const moduleName = file.name.substring(
      0,
      file.name.length - '.esdl'.length,
    );
    await DEFAULT_FILE.appendFile(`module ${moduleName} {\n`);
    for await (let line of f.readLines()) {
      await DEFAULT_FILE.appendFile(`    ${line}\n`);
    }
    await DEFAULT_FILE.appendFile(`}\n`);
    await f.close();
  }
}

generateFile().catch((err) => {
  console.error(err);
});
```

**Comment by elprans** [comment]
I'm not sure I understand the problem.  You can already do that with separate files in `dbschema`:

```
# user.esdl
module user {
  type User;
}

# default.esdl 
module default {
  type Blog {
    author: user::User;
  } 
}
```

Explicit imports are unnecessary, because all modules in `dbschema` are visible by default in every other module.  Though we should consider adding a way to alias them.

**Comment by Gobot1234** [comment]
Ah right, thank you for clarification, do you have a link to this in the docs, I must have missed it

**Comment by raddevon** [comment]
@elprans I think I  misunderstood when I suggested @Gobot1234 file this. I thought they wanted to be able to omit `module <name>` in each file and have the module's name mirror the file name of that schema file.
