### ISSUE TITLE
Reverse search behaving weirdly

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#115]
Typing in reverse search causes lines to be inserted for every typed character:

![record](https://user-images.githubusercontent.com/347119/89344504-d6f4f580-d65a-11ea-992c-a05745015b05.gif)

**Comment by tailhook** [comment]
Cannot reproduce this as of f9d05cf. This probably requires some special size of history entries or something....

**Comment by 1st1** [comment]
Just confirming that this happened to me once too. And I can't repro now. Elvis, can you backup your history file and see if Paul can repro this with it?

**Comment by elprans** [comment]
I cannot reproduce with the original repro.  That said I *can* still reproduce with a sufficiently narrow window (once the content touches the right border).
