### ISSUE TITLE
Ctrl+C while editing previous multiline query

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#116]
Ctrl+C does not clean the screen buffer while navigating a multiline query from history. See the screenshot:

![Screen Shot 2020-08-07 at 11 38 32 AM](https://user-images.githubusercontent.com/239003/89677645-ad2e0f80-d8a2-11ea-9a79-b0bbcd83ef4a.png)

**Comment by elprans** [comment]
It also seems to kill the connection unnecessarily.  ^C should ideally only reconnect if fired when the connection isn't idle.

**Comment by tailhook** [comment]
> It also seems to kill the connection unnecessarily. ^C should ideally only reconnect if fired when the connection isn't idle.

This was explicit decision, unless I've misunderstood something.

**Comment by 1st1** [comment]
> This was explicit decision, unless I've misunderstood something.

I don't remember us discussing this specific case. IMO ctrl+c should abort the current operation. In the case of a long running query -- cancel it. In the case of editing a multiline big query -- reset the edit.
