### ISSUE TITLE
DEL key does not work

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb-cli#117]
Version: `1.0.0-alpha.4+d20200806.g089f60fef`

DEL key should delete 1 character on the right from cursor position.

**Comment by tailhook** [comment]
Del k ey works for me. There is something peculiar with your platform that we might not support yet:
1. What is a platform and terminal emulator (GUI)?
2. On linux: try running `reset` command and then immediately `edgedb`. Does it work?
3. On linux: show the output of `stty` command

**Comment by Fogapod** [comment]
I'm using `st` terminal.
```sh
$ stty
speed 38400 baud; line = 0;
-brkint -imaxbel
```

Just checked a different one, this is indeed a terminal problem.
