### ISSUE TITLE
Add run once mode to `edgedb watch`

### ISSUE THREAD

**Issue by ssendev** [edgedb/edgedb-cli#1170]
Add a command line option to exit `edgedb watch` after running once. Which means it's actually not watching so maybe add it as another subcommand

This would be useful in scripts and is related to #1099

Currently can be faked with `edgedb watch 2>&1 | while read line; do; echo $line; echo "x$line" | grep -q 'Initialized. Monitoring' && pkill --parent $$ -x edgedb; done` but is pretty unclean

**Comment by raddevon** [comment]
This is available as the `--dev-mode` option on [`edgedb migrate`/`edgedb migration apply`](https://www.edgedb.com/docs/cli/edgedb_migration/edgedb_migration_apply).
