### ISSUE TITLE
EDGEDB_PASSWORD environment variable is not respected

### ISSUE THREAD

**Issue by niowniow** [edgedb/edgedb-cli#1174]
I'm trying to use the edgedb CLI to connect to a password-protected edgedb instance running in a docker container on port 5656
I can connect using the `--password` argument. However, the environment variable `EDGEDB_PASSWORD` seems not to be respected.

- EdgeDB Version: "3.0-rc.1+eeedba7"
- EdgeDB CLI Version: EdgeDB CLI 4.1.0-dev.1066+c02be5b

Steps to Reproduce:

1. Set environment variable and run query
```
export EDGEDB_PASSWORD=secret
echo $EDGEDB_PASSWORD
# secret
edgedb -P 5656  query 'select sys::get_version_as_str()'
# edgedb error: PasswordRequired: Password required for the specified user/host
```

Workaround:
Use `EDGEDB_DSN` environment variable

```
export EDGEDB_DSN=edgedb://edgedb:secret@localhost:5656
edgedb  query 'select sys::get_version_as_str()'
```

**Comment by niowniow** [comment]
A follow up. Connecting to an insecure instance appears to require the `EDGEDB_CLIENT_TLS_SECURITY=insecure` or the `EDGEDB_SERVER_SECURITY=insecure_dev_mode` environment variables to be set for connecting via DSN or password, respectively.
Not sure if we should spin this out into a separate issue, though

**Comment by elprans** [comment]
See https://github.com/edgedb/edgedb/issues/6454#issuecomment-1806539110 and #1179.  The solution is to specify connection parameters consistently, e.g. all on the command line or all in the environment, e.g:

```
export EDGEDB_PASSWORD=secret
export EDGEDB_PORT=<some-port>

edgedb query 'select sys::get_version_as_str()'
```

or

```
echo secret | edgedb -P 5656 --password-from-stdin query 'select sys::get_version_as_str()'
```

There is also a way to explicitly pull parameters from the environment into a DSN via the [_env suffix](https://www.edgedb.com/docs/reference/dsn#ref-dsn), e.g:

```
edgedb --dsn=edgedb://user@host/?password_env=EDGEDB_PASSWORD
```

**Comment by raddevon** [comment]
Closing for now. Please reopen, @niowniow, if this doesn't address your issue.
