### ISSUE TITLE
CLI does not execute pasted command if there is a comment at the end

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb-cli#118]
- EdgeDB Version: `1.0-alpha.4+dev.116.g83e9f530`
- EdgeDB CLI Version: `1.0.0-alpha.4+d20200806.g089f60fef`
- OS Version: Docker

Steps to Reproduce:

1. copy `SELECT 1; #`
2. paste into CLI
3. hit ENTER

**Comment by tailhook** [comment]
Fixed. Thanks!
