### ISSUE TITLE
Can't complete EdgeDB installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by Tembocs** [edgedb/edgedb-cli#119]
I'm trying to install EdgeDB in Ubuntu 20.04 on a x64 machine. I have successful run ```curl --proto '=https' --tlsv1.2 https://sh.edgedb.com -sSf | sh``` and ```source ~/.edgedb/env```. When trying to run ```edgedb server install``` I get the error message below.
```Error: failed to fetch repository index: HTTP error: Operation timed out (os error 110)```. 
I have a good internet connection and can download other things successful, including updating parts of the operating system. What exactly is the meaning of this as applied to EdgeDB installation and how can I solve this?

**Comment by tailhook** [comment]
In case the error still actual, try adding `RUST_LOG=info` to environment:
```
RUST_LOG=info edgedb server install
```
That should print the actual url:
```
[2020-08-11T10:25:17Z INFO  edgedb::server::remote] Fetching optional JSON at https://packages.edgedb.com/apt/.jsonindexes/focal.json
```
Then you can try fetching this URL manually and post it here in case the tool got URL wrong.

**Comment by tailhook** [comment]
Probably this was some temporary error. Reopen if this happens.

**Comment by tnRaro** [comment]
The same error occurred with Ubuntu 20.04.2 LTS on WSL2.

```
edgedb error: failed to fetch JSON at URL: https://packages.edgedb.com/apt/.jsonindexes/focal.json: failed to fetch repository index: HTTP error: Operation timed out (os error 110)
```
