### ISSUE TITLE
branch rebase printing output could be improved

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb-cli#1230]
Currently, branch rebase output looks like this:

```
➜  demo10 git:(feat-links) edgedb branch rebase main
OK: CREATE BRANCH
Rebasing m1x56iv2ej7twarsf7sfs5ydornaawo2uvwj6xzzwyj6qakodd2mrq as base
Rebasing m1ce4fakd5rmb5gnxba4mmznjjyxcivekktgmtm3dxxbmy7hbq5x5q as base
Rebasing m1jg66zlozm4kt74rrnofcpwwiw7e43qnwpl5adj6mgv5t3xml3yja as base
Rebasing m1cl5vqruxmatwlbjyrtougnb6t7ze65ssuvkp6553iey4dbma3zqq as feature onto m1jg66zlozm4kt74rrnofcpwwiw7e43qnwpl5adj6mgv5t3xml3yja
Updating migration m1cl5vqruxmatwlbjyrtougnb6t7ze65ssuvkp6553iey4dbma3zqq to m14hkktv5sghhmvv5xn2db7rgkdtw2w7vev42prfr6n5hbda7i2pfa
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00004.edgeql
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00003.edgeql
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00002.edgeql
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00001.edgeql
Applied m14hkktv5sghhmvv5xn2db7rgkdtw2w7vev42prfr6n5hbda7i2pfa (00004.edgeql)
OK: DROP BRANCH
Recreating branch feat-links...
OK: ALTER BRANCH
```

My nits:
- the `OK: CREATE BRANCH` and `OK: DROP BRANCH` could be more clear in what they are doing.
- `Rebasing m1x56iv2ej7twarsf7sfs5ydornaawo2uvwj6xzzwyj6qakodd2mrq as base` is not necessary to show
- `Updating migration m1cl5vqruxmatwlbjyrtougnb6t7ze65ssuvkp6553iey4dbma3zqq to m14hkktv5sghhmvv5xn2db7rgkdtw2w7vev42prfr6n5hbda7i2pfa` is very verbose, is it even necessary?
- `Writing` should only be printed for new migrations, and not any common migrations.

I would suggest something like:

```
Last common migration is m1jg66zlozm4kt74rrnofcpwwiw7e43qnwpl5adj6mgv5t3xml3yja in 00002.edgeql.
Since then, there are:
- 2 new migrations on target branch,
- 1 migration to rebase.

Creating new temporary branch, based on target: feat-links-rebase

New migrations on target branch:
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00002.edgeql
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00003.edgeql

Migrations to rebase:
Writing: /home/aljaz/EdgeDB/demo10/dbschema/migrations/00004.edgeql
Applied m14hkktv5sghhmvv5xn2db7rgkdtw2w7vev42prfr6n5hbda7i2pfa (00004.edgeql)

Replacing branch feat-links with feat-links-rebase
Done.
```

**Comment by aljazerzen** [comment]
#1225 made this much better:

![image](https://github.com/edgedb/edgedb-cli/assets/11072061/97ad82db-863f-43c6-a1e5-e72630bcbf5d)

@quinchs Why are `Writing: ` messages backwards? It would make more sense (to me) if they were in their order of application.

**Comment by quinchs** [comment]
Oh I think that's an artifact of `.enumerate.rev()`, which can be fixed for the printing

**Comment by aljazerzen** [comment]
Something strange is going on:
![image](https://github.com/edgedb/edgedb-cli/assets/11072061/6323683a-5895-4e78-93ac-f2a0bc51cf34)

**Comment by quinchs** [comment]
Fixed in https://github.com/edgedb/edgedb-cli/pull/1238
