### ISSUE TITLE
`edgedb branch create` should show nicer error messages for older server versions that don't support branches

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-cli#1232]
- EdgeDB Version: 3.0-rc.5+ca725cb
- EdgeDB CLI Version: repl 4.2.1-dev.1092+b2a234f

Steps to Reproduce:

```
$ edgedb branch create auth
Creating branch 'auth'...
edgedb error: EdgeQLSyntaxError: Unexpected 'schema' (on line 1, column 8)
  Server traceback:
...
```

See also: https://github.com/edgedb/edgedb-cli/issues/1226#issue-2171283698

**Comment by quinchs** [comment]
Implemented in https://github.com/edgedb/edgedb-cli/pull/1234
