### ISSUE TITLE
When switching to a branch from `main`, the name of the branch switched from is logged as `edgedb`

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#1255]
```
$ edgedb branch list
main - Current
feature
$ edgedb branch switch feature
Switching from 'edgedb' to 'feature'
```

- EdgeDB Version: 5.0-beta.2+796ed0e
- EdgeDB CLI Version: 4.3.0-dev.1112+20f80f4
- OS Version: macOS 14.0

Steps to Reproduce:

1. Start a new project
2. Open REPL and create a new branch with `create schema branch feature from main;` (currently required due to #1254)
3. Back out of REPL and switch to the new branch with `edgedb branch switch feature`

**Comment by quinchs** [comment]
This is due to 'edgedb' being written to `credentials.json` when an instance is created, I have changes for this, just not on my travel mac :(

**Comment by quinchs** [comment]
I'll get to this one when I'm back home
