### ISSUE TITLE
Add `edgedb list branches` as the branch analog to `edgedb list databases`

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#1275]
`list databases` does seem to work on v5 instances, but people may not know to use it since we are re-training them that databases are out and branches are in. Looks to me like `list branches` could just be an alias for `list databases` except that I guess it should probably fail on pre-v5.

**Comment by 1st1** [comment]
I think we should instead deprecate `list databases` and print a recommendation to use `branch list`

**Comment by raddevon** [comment]
Would we then make that command work for users on versions prior to 5 to list their databases, or would that recommendation not apply to the users who would have wanted to use `edgedb list databases` to list databases on a pre-v5 database? Either of those seems like awkward DX to me, but maybe there's a third option I'm not considering…
