### ISSUE TITLE
Add edgedb server authenticate as a way to create/repopulate the credentials file.

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#141]
Currently, we have `edgedb server reset-password` which only resets the password.  However, it is useful to be able to write other fields as well.

I propose replacing `edgedb server reset-password` with `edgedb server authenticate` which should take all necessary parameters from command line and record them appropriately in a credentials file.  This is useful for container-based deployments, where the configuration is passed as env vars or platform secrets, and the container entrypoint needs to call various CLI commands (think `edgedb migrate`) and then runs an app that connects via a language client.

**Comment by tailhook** [comment]
I'm not sure what you mean by "write other fields". If it's new user, than `create-role --save-credentials` should work (not implemented yet). You can't change the port (that easy). Only database may be changed easily (but have to be created too).

Creating a new credentials file is not implemented, but I'm not sure `authenticate` makes sense here. I named the command `save-credentials` (to mirror the parameter above), but yes we can search for a better name.

**Comment by elprans** [comment]
> I'm not sure what you mean by "write other fields".

I want to be able to give it the address, the user name and a secret, and have a functional credentials file after that.  Or, give some other way of obtaining the credentials (see below).

> I'm not sure `authenticate` makes sense here

`authenticate` works very well is you think about it in the terms of generating a `credentials` file for a hosted cloud instance, basically the same way `gcloud auth` works.

**Comment by elprans** [comment]
This is now implemented as `edgedb instance link`.
