### ISSUE TITLE
<datetime> that doesn't panic before 1970

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb-cli#174]
I've been using cal::local_time and the rest in the tutorial a lot because the setting is the 19th century, and a <datetime> before 1970 leads to a panic that kicks me out of the server along with a big ol' Rust backtrace. I took a look at it though and I see it comes from the humantime crate at line 247:

https://docs.rs/crate/humantime/2.0.1/source/src/date.rs

which starts out with a duration_since and an .expect():

```
impl fmt::Display for Rfc3339Timestamp {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use self::Precision::*;

        let dur = self.0.duration_since(UNIX_EPOCH)
            .expect("all times should be after the epoch");
```

Would be nice if the crate had something like a pub const FAKE_UNIX_EPOCH and an unwrap_or or a match where it uses UNIX_EPOCH in one case and FAKE_UNIX_EPOCH (a Unix epoch that starts at year 0 for example) in another.

**Comment by tailhook** [comment]
Okay, first I've tried to fix `humantime`, but that isn't going to support negative or greater than 9999 years. Crates I've looked at do not support postres full range of years `-4713..294276`: `chrono` (max year ~266000) and `time` (max year 100000). Looks like we have to make a custom formatter for this :(
