### ISSUE TITLE
Make it possible to connect via a DSN string

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#176]
We need a way to connect our REPL (and other tools) via a DSN string.

Ideally with

```
$ edgedb edgedb://...
```

If the above is problematic for some reason we could also do `$ edgedb --dsn edgedb://...`.

**Comment by tailhook** [comment]
Just realized that we need `edgedb --dsn edgedb://host.name create-migration` work. I don't think positional argument is a worthy special case for just the repl.

**Comment by 1st1** [comment]
> I don't think positional argument is a worthy special case for just the repl.

Can we make it a special case for the entire CLI? E.g. `edgedb dump edgedb://...`?

**Comment by tailhook** [comment]
It looks like we can for repl. But for everything it looks hard and sometimes might be weird, like:
`edgedb create-database new_db edgdb://` or `edgedb create-database edgedb:// new_db` or `edgedb edgedb:// create database new_db` ?

Also in bindings we accept bare instance name as `dsn`. And this ruins that assumption, as nothing stops you to define database named same as any other current or future command.
