### ISSUE TITLE
very long disconnect

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#178]
I connected to a remote edgedb instance and disconnecting REPL from it took quite some time (I think around 60 seconds). 

In the end I was presented with this message:

```
[2020-10-22T19:36:33Z WARN  edgedb::repl] Termination error: error reading data: Operation timed out (os error 60): Operation timed out (os error 60)
```

First, I think we should cap the termination to 5 seconds and just forcefully close the socket if we don't receive response by then.

Second, the error message has "Operation timed out (os error 60)" repeated two times. Let's investigate why it's repeated and fix.

Lastly, it's not clear that 60 is an ERRNO. I'd change it to "Operation timed out (ETIMEOUT)"

**Comment by tailhook** [comment]
> Lastly, it's not clear that 60 is an ERRNO. I'd change it to "Operation timed out (ETIMEOUT

This is how Rust formats IOError. I don't think we need to reimplement that part just to slightly tweak the message. Anyway if we enforce timeout, this message won't be same (i.e. we will not get os error).
