### ISSUE TITLE
Rebasing local migrations

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#196]
When developing locally sometimes it makes sense to edit schema multiple times and then ship single migration. Another important use case is switching and merging branches.

While it could be achieved by wiping the database (and having scripts to populate some test data) it's often inconvenient. Especially for smaller projects. What we can do for smaller projects is backup of the database before applying migration:

```
edgedb migrate --backup-dir=./tmp/backups
```
This would create a file like `./tmp/backups/m1uimtsee7v4qx7jpjihbfqgmutc74zv2umx67ohpbwow3rsal4lna.dump`.

Then to restore you do something along the lines:
```
git clean dbschema/migrations
edgedb drop-database myapp
edgedb create-database myapp
edgedb restore -d "./tmp/backups/$(edgedb get-last-revision).dump"
```

To clarify, I don't propose to include the script into edgedb, just the parts that are hard to do with scripts:
1. `--backup-dir` parameter
2. `edgedb get-last-revision` command, which returns id from the last revision in the filesystem regardless of what is in the DB and regardless of the schema changes
3. Alternatively or in addition to (2) we can have `edgedb revisions --newer-first --from-fs --limit 5` which would allow to restore from older backup if there is no latest one.

**Comment by elprans** [comment]
> `--backup-dir` parameter

Why should this be a CLI option?  Wouldn't `edgedb dump ./tmp/backups/ && edgedb migrate` achieve the same?

> `edgedb revisions --newer-first --from-fs --limit 5`

This seems reasonable.  Although I'd call this `migration-log` or something like that.
