### ISSUE TITLE
Is \s command implemented?

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#20]
There's nothing happening for me when I run the `\s` command.

**Comment by tailhook** [comment]
That's weird. I've caught this bug once too. But now I can't reproduce it again and history works well. But anyway:
1. Do you have `less` in `PATH`?
2. Do you have `$PAGER` in env?
3. Do you have something in history? (i.e. have you tried something in this session)
4. Does history at all works for you? (i.e. up arrow key)

**Comment by 1st1** [comment]
>    Do you have less in PATH?

yes

> Do you have $PAGER in env?

no

> Do you have something in history? (i.e. have you tried something in this session)

yes

> Does history at all works for you? (i.e. up arrow key)

yes

**Comment by tailhook** [comment]
Well, it turned out that less than a screen of history had this bug, that's why it's hard to reproducd :) Fixed.
