### ISSUE TITLE
Auto-install system prerequisites required for native package installation

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#206]
Currently, on a virgin Ubuntu system, `edgedb server install` fails with:

```
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
edgedb error: Command "/usr/bin/sudo" "apt-key" "add" "-" exit code: 255
```

To avoid this, we should `apt-get gnupg` and the other necessary components required to proceed with the installation.  This applies to all other distros we support.

**Comment by tailhook** [comment]
I think we have briefly discussed that and rejected initially.

There is probably a reason why gnupg is not a dependency of apt-key? And is also unclear what exact gnupg to install?

**Comment by elprans** [comment]
Well, it creates unnecessary friction during first-time install.  Granted, most real systems would have gnupg installed, but if not `apt-get install gnupg` pulls in the correct version on distros we support.

**Comment by 1st1** [comment]
bumping this, I think it would be great to fix this.
