### ISSUE TITLE
edgedb self-upgrade missing a / in url

### ISSUE THREAD

**Issue by squili** [edgedb/edgedb-cli#209]
- EdgeDB Version: 1-alpha7-a678bf8
- EdgeDB CLI Version: 1.0.0-alpha.7 (error also present in 1.0.0-alpha.6)
- OS Version: Linux Mint 20

Steps to Reproduce:

1. Install latest CLI
2. Attempt a forced `self-upgrade`

Error:

`edgedb error: cannot download https://packages.edgedb.comarchive/linux-x86_64/edgedb-cli_1.0.0-alpha.7_2020121404 -> (home path)/.edgedb/bin/edgedb.download: failed to lookup address information: Name does not resolve`

Notes:

I've tracked down the issue to line 143 in `self_upgrade.rs`. It seems the remote was supposed to add a `/` to the start of the `installref`, but it doesn't follow this behaviour. I fixed this locally by adding a `/` before the `{}`.

**Comment by tailhook** [comment]
This was broken in edgedb/edgedb-pkg@d495d810. @ambv, @elprans was this done intentionally?

(I'm going to fix this my side anyway, because this is a security issue, but JSON's might need fixing anyway, and fixing them would fix upgrading from old versions of the CLI)

**Comment by 1st1** [comment]
> This was broken in edgedb/edgedb-pkg@d495d81. @ambv, @elprans was this done intentionally?

Do you build the URL in rust? If so need to use some lib to concatenate fragments properly and perhaps sanitize them.

**Comment by tailhook** [comment]
> > This was broken in [edgedb/edgedb-pkg@d495d81](https://github.com/edgedb/edgedb-pkg/commit/d495d81). @ambv, @elprans was this done intentionally?
> 
> Do you build the URL in rust? If so need to use some lib to concatenate fragments properly and perhaps sanitize them.

Yes, that makes sense. Although, relative URLs in this case are even more confusing. Are they relative to the root (so just missing slash) or to the JSON that refers to them? Anyway, that's fixed in #213

**Comment by elprans** [comment]
> Although, relative URLs in this case are even more confusing

This wasn't intentional and fixed in edgedb/edgdeb-pkg#43.
