### ISSUE TITLE
Exceptions lead to segfault or stalled repl

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#25]
Here's one example:

![Screen Shot 2020-04-11 at 1 09 41 PM](https://user-images.githubusercontent.com/239003/79053914-c9bc8280-7bf5-11ea-8776-c442455b087a.png)

I found that repl can hang or segfaul when processing exceptions from the server. The problem is that this is very intermittent and non-consistent.

**Comment by tailhook** [comment]
Well, works fine for me:
![no-crash](https://user-images.githubusercontent.com/321799/79145220-f674c380-7dc8-11ea-813c-21a692e93cc4.jpg)
The only issue is extra brace at the start which I've just fixed now.

**Comment by tailhook** [comment]
If only you and @ambv have this issue. This is probably something OSX specific :( Can you run gdb and show the stack trace? I may only guess that backtrace-capturing library has some issue on OSX. We can try to make backtraces optional as a workaround.

**Comment by ambv** [comment]
I'll look into giving you a system stack trace. Apple is a clang shop so we'll see if it will be through gdb or lldb.

**Comment by 1st1** [comment]
I can't repro this now.

**Comment by tailhook** [comment]
It could be this one: https://github.com/rust-lang/rust/issues/71397
Let's close it for now as we don't have anything actionable here now.
