### ISSUE TITLE
Enabling debug mode with environment variables

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb-cli#252]
I've seen this part of the code, though wasn't able to actually test it (tried to set it, but dunno how it even works and I believe it is not documented either);
https://github.com/edgedb/edgedb/blob/c972896825c855393080f1a07f1b9eda1781d09a/edb/common/debug.py#L178-L193

One thing that might be really cool is that, somehow setting this on the repl. Like `\debug edgeql_compile` etc.

**Comment by elprans** [comment]
Those are server debug flags, intended to be used like this:

In development:

```
env EDGEDB_DEBUG_EDGEQL_COMPILE=1 edb server -D <data-dir>
```

For non-dev non-docker installs this should also work:

```
env EDGEDB_DEBUG_EDGEQL_COMPILE=1 edb server start --foreground <instance_name>
```

**Comment by isidentical** [comment]
Oh, thanks! I thought it was for the client.
