### ISSUE TITLE
improve the "cannot establish connection" message

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#256]
When `edgedb` repl command is fired up it prints the

```
Connecting to an EdgeDB instance at localhost:5656...
```

message. And in the case that the user forgot to type `edgedb server install` it would hang for 30 seconds, until printing 

```
edgedb error: cannot establish connection for 30s: Connection refused (os error 61)
```

-----

I suggest to improve this flow a bit and make it more user friendly.  Say the user types the `$ edgedb` command.

**Flow 1**: we detect that there's no edgedb server installed locally via `edgedb server install`.

1. When `edgedb` repl command is fired up it should pring the
   ```
   Connecting to an EdgeDB instance at localhost:5656...
   ```

2. If the connection cannot be established right away, it should print another message:
   ```
   Connecting to an EdgeDB instance at localhost:5656...

   Attempting to connect for 30 more seconds...

   There seems to be no EdgeDB server installed locally. 
   Did you run the `edgedb server install` command?
   ```

3. After 30 seconds, it should print:
   ```
   Connecting to an EdgeDB instance at localhost:5656...

   Attempting to connect for 30 more seconds...

   There seems to be no EdgeDB server installed locally via 
   the `edgedb server install` command.  Have you run it?

   edgedb error: could not establish connection for 30s: Connection refused (os error 61)
   ```

------

**Flow 2**: there's at least one EdgeDB server installed locally.

1. When `edgedb` repl command is fired up it should pring the
   ```
   Connecting to an EdgeDB instance at localhost:5656...
   ```

2. If the connection cannot be established right away, it should print another message:
   ```
   Connecting to an EdgeDB instance at localhost:5656...

   Attempting to connect for 30 more seconds...
   ```

3. If the connection cannot be established for 3 more seconds we print additional message:
   ```
   Connecting to an EdgeDB instance at localhost:5656...

   Attempting to connect for 30 more seconds...

   Still cannot connect.  Troubleshooting:  

   * Check if an EdgeDB server instance is running with `edgedb server status`.
   * Connect to the particular instance with `edgedb -I <INSTANCE NAME>`
   ```

3. If the connection could not be established after 30 seconds we ultimately print:
   ```
   Connecting to an EdgeDB instance at localhost:5656...

   Attempting to connect for 30 more seconds...

   Still cannot connect.  Troubleshooting:  

   * Check if an EdgeDB server instance is running with `edgedb server status`.
   * Connect to the particular instance with `edgedb -I <INSTANCE NAME>`

   edgedb error: could not establish connection for 30s: Connection refused (os error 61)
   ```

---------

@elprans thoughts?

**Comment by elprans** [comment]
> we detect that there's no edgedb server installed locally via `edgedb server install`.

The suggestion here might be confusing and misleading if you happen to run Docker images directly.

**Comment by 1st1** [comment]
> if you happen to run Docker images directly.

We can clarify that in the connect message.  Changed to

```
   There seems to be no EdgeDB server installed locally via 
   the `edgedb server install` command.  Have you run it?
```

Ultimately I'm more concerned optimizing the flow that 90% of the users would follow.

**Comment by elprans** [comment]
Hm. Well, `edgedb server install` doesn't, in fact, install on `5656`, so you are supposed to run `edgedb -I my_instance` instead, and in _that_ case we can surely say there's no instance `my_instance`

**Comment by 1st1** [comment]
Actually we want this suggestion to implemented for all `edgedb *` commands. Another example:

```
~/d/e/bench » edgedb migrate
Connecting to an EdgeDB instance at localhost:5656...
```

As a new user I could stuck here without any idea what I'm doing wrong.  We can also look at all instances we have locally and explicitly suggest the user to connect to them:

```
~/d/e/bench » edgedb migrate
Connecting to an EdgeDB instance at localhost:5656...

You have the "bench" instance of EdgeDB running at localhost:10700. 
If you want to work with it do `edgedb -I bench migrate`
```

**Comment by tailhook** [comment]
When using `edgedb` it doesn't mean you connect to `edgedb server installed` instance, you could connect to:
1. Remote server
2. A docker container spawned by docker compose (which is also a common case)
3. A instance in the same docker container (our default Dockerfile use it)
4. Local server, but not user installation (because we don't manage system installations)
5. And eventually our cloud

Making things very confusing for every user outside of tutorial scenario is bad.

I think users usually smart enough to figure out that to connect to server they have to run the server.

We still can improve some things here, but being to chatty may be as confusing, especially if it's a script or docker-compose run, where you just wait 30 seconds and everything is just fine.

People will try to hide our logs we are to chatty, and therefore making issues harder to diagnose for us.

**Comment by 1st1** [comment]
> Remote server
> And eventually our cloud

Will those always run on 5656? What about the hostname? I assume it won't be `localhost`. So again, what's the point of connecting to localhost:5656 by default?

> People will try to hide our logs if we are too chatty, and therefore making issues harder to diagnose for us.

We can only be chatty when we know we're running in interactive mode (check the stdout if it's a tty).

**Comment by tailhook** [comment]
> > Remote server
> > And eventually our cloud
> 
> Will those always run on 5656? What about the hostname? I assume it won't be `localhost`. So again, what's the point of connecting to localhost:5656 by default?

This is a different issue, we're discussing messages here.

> 
> > People will try to hide our logs if we are too chatty, and therefore making issues harder to diagnose for us.
> 
> We can only be chatty when we know we're running in interactive mode (check the stdout if it's a tty).

It's not reliable. Script running on the terminal still has tty on stdout (as well as docker container run with `-it`, which is very common thing to use without thinking, and is useful to get Ctrl+C working), unless you explicitly run it with `< /dev/null`. Not sure about docker compose defaults.

**Comment by 1st1** [comment]
> This is a different issue, we're discussing messages here.

It's a closely related one. Depending on the outcome of the discussion about localhost:5656 being the default we decide if we want to do anything about this particular issue.

**Comment by tailhook** [comment]
> > This is a different issue, we're discussing messages here.
> 
> It's a closely related one. Depending on the outcome of the discussion about localhost:5656 being the default we decide if we want to do anything about this particular issue.

I don't see how we depend on that. The issue with `-I` is that we agreed that it's not just local instance, it refers to a credentials file. You can use add host there. And we'll have command that writes credentials file for the remote host for you.

I think it's mostly `init-project` that will solve this issue better.

**Comment by 1st1** [comment]
Superseded by https://github.com/edgedb/edgedb-cli/issues/267
