### ISSUE TITLE
unclear migrate command help text

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#259]
I am trying to figure out how to roll back a migration. The migrate command help seems to indicate that it can "Bring current database to ... a specified revision" but it doesn't seem to indicate how to specify a revision. It seems that either there should be some explanation of how to specify a revision, or that part should be removed from the help text. 

```
$ edgedb -I workout migrate --help
edgedb-migrate
Bring current database to the latest or a specified revision

USAGE:
    edgedb migrate [FLAGS] [OPTIONS]

FLAGS:
    -h, --help     Prints help information
        --quiet    Do not print any messages, only indicate success by exit status

OPTIONS:
        --schema-dir <schema-dir>    Directory where *.edgeql files are located [default:
                                     ./dbschema]
```

- EdgeDB Version: N/A
- EdgeDB CLI Version: edgedb-cli 1.0.0-beta.1
- OS Version: Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tailhook** [comment]
Yes it's unimplemented feature. I'll take a look if implementing it is easy enough instead of fixing the message.
