### ISSUE TITLE
Trim trailing ';' for \d and similar commands

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#26]
Having a trailing `;` currently leads to an error that takes some time to decipher. We need to trim trailing `;` for `\d` and other commands accepting `PATTERN`.

![Screen Shot 2020-04-11 at 1 15 16 PM](https://user-images.githubusercontent.com/239003/79054018-8adafc80-7bf6-11ea-8bf3-a72d8b540cdb.png)

**Comment by tailhook** [comment]
Well, firstly I've thought to just strip semicolon. But then it's unclear if `\d Object; SELECT 1` should work and if it should work as ```\d `Object; SELECT ` ```

So I think we should figure out these first:
1. #6 -- this would change parsing of the arguments at all under my proposal
2. #2 -- this would introduce two-argument commands under @1st1's proposal

Both would lead to making `\d x y` illegal and so `\d x; select 1` is unambiguous. Or maybe not, then we'll review this issue again.

**Comment by tailhook** [comment]
#31 resolves the questions above
