### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#260]
It seems like the part that says "If you tried to supply `00003` as a PATTERN use `-- 00003`" is misleading since this command doesn't seem to accept patterns. Perhaps that pattern suggestion should be omitted if the command doesn't accept patterns? 

```
$ edgedb -I workout migrate -- 00003
error: Found argument '00003' which wasn't expected, or isn't valid in this context

If you tried to supply `00003` as a PATTERN use `-- 00003`

USAGE:
    edgedb migrate [FLAGS] [OPTIONS]

For more information try --help
```

- EdgeDB Version: N/A
- EdgeDB CLI Version: edgedb-cli 1.0.0-beta.1
- OS Version: Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tailhook** [comment]
Yes, rust's clap says it on every unexpected argument. I'm not sure where this `PATTERN` comes from. I'll take a look.
