### ISSUE TITLE
Feature request: SHIFT+ENTER executes query ignoring cursor position 

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb-cli#262]
This is a tiny QOL improvement, I often find it annoying how hitting enter splits your input at cursor position.
Every other CLI I know does not do this (python, psql, redis-cli, mysql, cmd, powershell. all linux shells etc).

I'm not saying it's wrong, but I think this can be improved. What if SHIFT+ENTER executed query without splitting? This is faster than hitting END+ENTER and is intuitive. SHIFT usually blocks ENTER adding newline instead, in this case this can be reversed.

**Comment by elprans** [comment]
`Alt+Enter` executes without splitting.

**Comment by Fogapod** [comment]
It works. Thanks. Is there a documentation for such features somewhere or not yet?

**Comment by tailhook** [comment]
> It works. Thanks. Is there a documentation for such features somewhere or not yet?

I don't think so. Where would you expect it to be documented?

**Comment by Fogapod** [comment]
I don't know, hotkeys section somewhere in online docs?

**Comment by elprans** [comment]
I'd include some help on interactive features of REPL in `\?`
