### ISSUE TITLE
Remove the default for the `-H` command line option

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#267]
The `edgedb` CLI shouldn't try to connect to localhost:5656 by default. The default advertised way of installing EdgeDB locally is to use the `edgedb server install` path, which spawns the DB on a random port. Which means that if the user forgets to specify the `-I` argument, the tool should ask if they want to connect to an instance (provide the `-I` argument) or to a TCP port (provide the `-H` argument).

**Comment by tailhook** [comment]
Merged together with `project init`.
