### ISSUE TITLE
Server init: `Load failed: 5: Input/output error`

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-cli#287]
#### This issue is being opened for visibility reasons. 

Users running macOS Big Sur will see `Load failed: 5: Input/output error` when running `edgedb server init`. This is a non-fatal error resulting from [a bug in Big Sur](https://developer.apple.com/forums/thread/665661). Your EdgeDB instance has been created successfully, even if you see this error.

- EdgeDB Version: beta 1
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Install `edgedb` as instructed in [the docs](https://www.edgedb.com/docs/tutorial/install#ref-tutorial-install)
2. Run `edgedb server init my_instance`

**Comment by martianmartian** [comment]
"The problem was that the file included special characters which i tried to execute with launchctl. After I removed the bad characters the plist loaded successfully.
Check with "plutil" for proper file format."

the plist file was broken for me. replaced with a healthy one, started working

**Comment by tailhook** [comment]
> "The problem was that the file included special characters which i tried to execute with launchctl. After I removed the bad characters the plist loaded successfully. Check with "plutil" for proper file format."
> 
> the plist file was broken for me. replaced with a healthy one, started working

`plutil -lint filename` shows `OK` for me on Big Sur. Can you be more specific what's broken? (i.e. putting an output or error message here)
