### ISSUE TITLE
Un-hardcode configuration parameters from `edgedb-repl/commands/configure`

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#3]
Currently, the configuration properties are hardcoded.  This is suboptimal because the number of config options will grow, and adding new options will require new CLI releases.  Consider implementing the `CONFIGURE` calls the way they are in the Python REPL.

**Comment by tailhook** [comment]
There is a codegen for command-line options, so adding an option is adding two things, an option with description:
```
    /// The amount of memory used by internal query operations such as sorting.
    ///
    /// Corresponds to the PostgreSQL work_mem configuration parameter.
    QueryWorkMem(ConfigStr),
```
And a match case:
```
        C::Set(Set { parameter: S::QueryWorkMem(param) }) => {
            set_string(cli, "query_work_mem", param).await
        }
```
Which is kinda simple enough. Unfortunately resetting option takes another two things:
```
    /// Reset work_mem postgres configuration parameter to default value
    QueryWorkMem,
```
```
                C::QueryWorkMem => "query_work_mem",
```

So generally:
1. For simple options, code boils down to name, type and description
2. Complex options like `listen_addresses` require their own code anyway

So I think more codegen would only complicate the code and maintenance.

On the other hand, we can make a test which runs `configure set --help` and checks that all options are present.

**Comment by elprans** [comment]
@tailhook I still don't think that autocomplete and help are worth the extra effort of maintaining explicit enums in CLI in the long term, but I'm fine with keeping the status quo until (and if) this becomes too annoying.  Adding a test for CLI exhaustiveness would be a good way of keeping it in shape for now.
