### ISSUE TITLE
Display commands statuses

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#30]
```
yury> CONFIGURE system insert Port {
.....   protocol := 'tutorial',
.....   database := 'yury',
.....   port := 3001,
.....   user := 'http',
.....   concurrency := 4,
..... };
WARNING: unsolicited message ReadyForCommand(ReadyForCommand { headers: {}, transaction_state: NotInTransaction })
  -> CONFIGURE SYSTEM: Ok
```

**Comment by tailhook** [comment]
This looks like result of the previous error which handled incorrectly. I fixed that. If it's a different error please reopen the issue.

*(generally its better to reimplement the whole Sync/Error handling in Rust/CLI, but I'm waiting for working Flush to do the work on that)*

**Comment by 1st1** [comment]
> but I'm waiting for working Flush to do the work on that

Sounds good.

Can we also change the formatting of

```
  -> CONFIGURE SYSTEM: Ok
```

to how it was in our Python repl:

```
CONFIGURE SYSTEM
```

with grey font.

No need to display the arrow and 'Ok' -- it's visual clutter.

**Comment by tailhook** [comment]
It's not just visual clutter:

1. It makes apart statuses from data, e.g. in a script:
```
edgedb> SELECT 1; CREATE TYPE Test44; SELECT 2;
{1}
  -> CREATE: Ok
{2}
edgedb>
```
2. The (1) is more important with other output modes, e.g. `tab-separated`, where there is no braces or other clutter that encloses data.
3. Bare `CONFIGURE SYSTEM` looks like debugging print which goes from somewhere. I've thought something like `Operation Status: Ok`. But this is something neutral that I could come up with.

Generally I'm okay with changing it somehow, but bare text isn't something that is clear enough for a new user.

**Comment by 1st1** [comment]
> Generally I'm okay with changing it somehow, but bare text isn't something that is clear enough for a new user.

I see your points.

First, let's change `Ok` to `OK`. I'd also reverse the order: `OK: START TRANSACTION`.  In my opinion `->` is not needed.  And please let's change the rendering color to gray in REPL mode.
