### ISSUE TITLE
Implement command-line semantics for backslash commands

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#31]
In particular:
* Semi-colon `;` ends the command, but it's optional, newline ends too
* `\d xx yy` is a command with two arguments, `xx` and `yy` not single `xx yy` as was previously
* Flags are now dash prefixed:
  * `S` -> `-s` or `--system`
  * `+` -> `-v` or `--versbose`
  * `I` -> `-I` or `--case-sensitive` (but see https://github.com/edgedb/edgedb-cli/issues/6#issuecomment-617746749)

**Comment by 1st1** [comment]
I mentioned this in https://github.com/edgedb/edgedb-cli/issues/6#issuecomment-617970644: I don't think we need long options like `--system` for REPL commands. REPL commands are one shot commands: a user quickly types them and moves on. I really don't see a case when someone types in long command options like `\d --verbose --case-sensitive foo` as opposed to `\d -v -I foo`

**Comment by tailhook** [comment]
> I mentioned this in [#6 (comment)](https://github.com/edgedb/edgedb-cli/issues/6#issuecomment-617970644): I don't think we need long options like `--system` for REPL commands. REPL commands are one shot commands: a user quickly types them and moves on. I really don't see a case when someone types in long command options like `\d --verbose --case-sensitive foo` as opposed to `\d -v -I foo`

Well, it looks like your personal preference. I never do `\d` it's easier to type `\describe` for me. And I can only remember `-s` because this is an alias of `--system`. And if I don't recall that, I just type `--<tab>` and see what completion options are, whereas shorter options aren't descriptive. It would be nice to have completion with descriptions like zsh has, but we can't do that right now.

Also I very much prefer long form `edgedb list-object-types --system` in scripts. So we have long form of arguments anyway. There is no reason to disable them in backslash commands.

**Comment by elprans** [comment]
I agree with Paul that there's no detriment to supporting long versions in repl. With completion, the discoverability of options would be better.

**Comment by 1st1** [comment]
> Also I very much prefer long form edgedb list-object-types --system in scripts. So we have long form of arguments anyway. There is no reason to disable them in backslash commands.

Alright, let's keep them!
