### ISSUE TITLE
Formatting and copy

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-cli#319]
### Simplify follow up messaging

- Explicit defaults: I don't think we can assume all developers are familiar with the `[default value]` convention in interactive CLIs
  - Old: Specify the name of EdgeDB instance to use with this project [test_project]
  - Old: Specify the name of EdgeDB instance to use with this project [default: test_project]
- Type of EdgeDB
  - Old: What type of EdgeDB instance would you like to use
  - New: How would you like to run EdgeDB for this project?
- Choice prompt
  - Old: "Your choice?"
  - New: "Type a number to select an option:"
  - Old: "Please enter number"
  - New: "Please enter a number."
- Formatting: consider adding some formatting to the messages and a `>` prompt so it’s a bit more user-friendly:
    ```
    No `edgedb.toml` found in `~/my_project` or above.
    Do you want to initialize a new project? [Y/n]
    > y
    
    What type of EdgeDB instance would you like to use with this project?
    1. Local (native package)
    Type the number of your selection:
    > 1
    
    Checking EdgeDB versions...
    Specify the version of EdgeDB to use with this project [1-beta1]:
    >
    ```
- Don't start line with backtick to improve readability
  - Old: `edgedb.toml` not found
  - New: No `edgedb.toml` found
- Project re-initialization
  - Old: Found `edgedb.toml` in /path/to/edgedb.toml
  - New: 
     ```
     Found `edgedb.toml` in /path/to/toml.
     Re-initializing project.
     ```
- Post-init instructions
  - Old: “To connect run either of edgedb or edgedb -I my_instance”
  - New: “To connect to my_instance, just run `edgedb`".
  - New (with `--project-dir`): "To connect to my_instance, navigate to {project_dir} and run `edgedb`"

**Comment by tailhook** [comment]
> Project re-initialization 

I'm not sure that "Re-initializing project" is right term here. We're initializing project on this machine (for the first time). Creating `edgedb.toml` is kinda "creating new project".

**Comment by tailhook** [comment]
Done in #321 

This might be subjective, but it looks a bit misleading for me:
```
Specify the name of EdgeDB instance to use with this project [default: test_5]:
> test1
Do you want to use existing instance "test1" for the project? [Y/n]
> y
```
In first case, default is too far at the right, so at a glance it looks like I have to write something, instead of just pressing enter.

And in the second prompt, this looks like some text expected from me, but not just bare y,n.

**Comment by colinhacks** [comment]
Re: "re-initializing" — good point, I agree. Skip this.

Re: defaults—

My problem with the current approach is that the convention of putting the default value in [brackets] is not something everyone is familiar with. If someone wasn't aware of this convention, they'd be very confused by what's happening. Think about the high schooler who's trying to learn web development for the first time. So adding `default: ` is worth the extra characters so it's clear to the user regardless of their familiarity with tools like this. 

Perhaps the best approach is to spell everything out for the user:

```
Specify the name of EdgeDB instance to use with this project, or leave blank for default (test_5):
> 
Do you want to use existing instance "test1" for the project? Type 'y' or 'n'.
> 
```

Perhaps @1st1 has thoughts here?

Another thought: is there a reason the `Y` capitalized in `[Y/n]`? 

Re: formatting — It's definitely a subjective thing. I don't get the sense that it's expecting more than a simple `y/n` personally. In any case I think it's a worthwhile tradeoff regardless:
- It makes it clear that some sort of interaction is expected. In the old version it isn't obvious that the user is supposed to type something. This is a complaint I've heard about interactive CLIs before.
- It makes the output a lot easier to read and the whole experience feel friendlier.

**Comment by tailhook** [comment]
> Perhaps the best approach is to spell everything out for the user:

Well, we're missing obvious. Since I've already started using rustyline for these prompts, defaults should just come prefilled.

> Another thought: is there a reason the Y capitalized in [Y/n]?

It's supposed to be default, but maybe we don't obey that somewhere. Should recheck.

**Comment by 1st1** [comment]
> Perhaps @1st1 has thoughts here?

I'm so used to things in `[]` in interactive CLI tools that it's hard to me to imagine that someone might be confused by that. That said, I'm not sure how modern JS tools approach this, maybe `[]` are things of the past?

**Comment by 1st1** [comment]
> Well, we're missing obvious. Since I've already started using rustyline for these prompts, defaults should just come prefilled (i.e. it's already there and you may edit or delete that value).

Need to try the new version with rustyline
