### ISSUE TITLE
`project unlink` doesn't work on windows 10

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-cli#326]
- EdgeDB CLI Version: edgedb-cli 1.0.0-beta.1+d20210503.ga13d7799e
- OS Version: Windows 10 (2004)

Steps to Reproduce:

1. Run `edgedb project init` as in https://github.com/edgedb/edgedb-cli/issues/325
2. Run `edgedb project unlink`. This runs without any errors, but the associated dir in `.edgedb/projects` isn't removed, and subsequently running `edgedb project init` in the same project directory fails with `edgedb error: project dir already exists`

**Comment by jaclarke** [comment]
I think there are actually two bugs here. I think the first is the same as #325, where it's not finding the path correctly, so it can't remove the directory, and the second is that it doesn't warn when you try to unlink a project (that has a edgedb.toml) that doesn't have an entry in `.edgedb/projects`.

**Comment by tailhook** [comment]
Should be closed by #328
