### ISSUE TITLE
some decimal values are rendered incorrectly

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#33]
```
yury> select 1e100n;
{1n}
```

**Comment by tailhook** [comment]
Generally this is fixed in 6b6a476 by https://github.com/edgedb/edgedb-rust/commit/96b8b0cd96661627c822fe6c17a0f9d920ba12f5. Except you can't write literally request above until https://github.com/edgedb/edgedb/pull/1372 is landed. `SELECT <bigint>'1e100n'` works though.
