### ISSUE TITLE
Running `edgedb project init` in initialized project throws

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-cli#334]
- EdgeDB Version:
- EdgeDB CLI Version:
- OS Version:

Steps to Reproduce:

1. Create new directory and `cd` into it
2. Go through `edgedb project init`
3. Run `edgedb project init` again

```sh
$ edgedb project init
Found `edgedb.toml` in `/Users/colinmcd94/Desktop/asdlfkj`
Initializing project...
edgedb error: project dir already exists
```

Can we catch this error and present a friendlier message? Something like: 

```ts
$ edgedb project init
Found `edgedb.toml` in `/Users/colinmcd94/Desktop/asdlfkj`
Initializing project...
Project already initialized.
$ 
```

**Comment by tailhook** [comment]
Not sure what exactly do you mean. We change the phrasing, but:
1. I think this is still an error, having error exit code (i.e. you might want `--non-interactive` init with specific parameters which we ignore on existing project)
2. So we keep `edgedb error` prefix.

**Comment by colinhacks** [comment]
Sounds good to me.
