### ISSUE TITLE
Bad error message when `edgedb.toml` exists but project not inited

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#335]
Steps to Reproduce:

1. Check out a repo that has an `edgedb.toml`
2. Run `edgedb`

We get
```
edgedb error: error reading project settings: No such file or directory (os error 2)
```

I think we should talk about `edgedb project init` in this error message?

Also, the first time I encountered this was when I was testing what happens when renaming a source directory. It could be good to surface a workflow for continuing to use the same instance?

**Comment by tailhook** [comment]
> Also, the first time I encountered this was when I was testing what happens when renaming a source directory. It could be good to surface a workflow for continuing to use the same instance?

Run `project init` and specify existing instance name. So suggesting running `project init` is okay?
