### ISSUE TITLE
Stopping EdgeDB instance hangs in CentOS 8.2 or above in Docker

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb-cli#349]
- EdgeDB Version: 1.0-beta2 (CentOS package)
- EdgeDB CLI Version: 1.0-beta2
- OS Version: Docker centos:8.2.2004

Steps to Reproduce:

https://bugs.centos.org/view.php?id=17461#c38441

This is causing our nightly test to fail. A workaround would be to wait for all compiler workers to exit before exiting the main process (the example workaround in the CentOS bug report should use a signal handler), so that systemd would properly receive the "cgroup is empty" event and mark the service as stopped.

Refs: https://github.com/lxc/lxd/issues/7539

**Comment by tailhook** [comment]
Hm, I'm not sure why it worked better in older systemd. But I don't think this is a workaround. I think this is expected unix behavior: the process which starts anything kills children and waits for them to complete (sans "daemon" use case, which I don't think applies here).
