### ISSUE TITLE
Validate credential existense when the server is starting up

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#354]
I'm not sure what happened here and why the credential file doesn't exist anymore. Perhaps I dropped my `~/.edgedb` directory. In any case, I think we should validate that the credential file exists when we start an instance.

```
{edgedb} ~/d/e/rfcs (master *) » edgedb server status
┌───────┬───────┬─────────┬─────────────┐
│ Name  │ Port  │ Version │   Status    │
├───────┼───────┼─────────┼─────────────┤
│ bench │ 10700 │ 1-beta1 │ not running │
└───────┴───────┴─────────┴─────────────┘

{edgedb} ~/d/e/rfcs (master *) » edgedb server start bench

{edgedb} ~/d/e/rfcs (master *) » edgedb -I bench
edgedb error: cannot read credentials file /Users/yury/.edgedb/credentials/bench.json: could not read file `/Users/yury/.edgedb/credentials/bench.json`: No such file or directory (os error 2)
```

**Comment by tailhook** [comment]
I don't think we should:

1. Technically you may have two different credential files that refer to an instance with different roles, and then drop one of them  and use another.
2. To execute `reset-password` the instance has to be running.

So while we create credentials file by default, it doesn't mean those files are so much tighly coupled.

We can print a warning, but maybe it's better to just suggest `reset-password`? Or both?

**Comment by 1st1** [comment]
I think suggesting reset-password makes sense
