### ISSUE TITLE
μs not supported as duration units

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#357]
It seems like it would make sense to support `μs` as duration units especially since that is how the cli prints it. 

```
edgedb> SELECT <duration>'1us';
{1µs}
edgedb> SELECT <duration>'1μs';
ERROR: InvalidValueError: invalid input syntax for type std::duration: "1μs"
```

- EdgeDB Version: 1.0a8.dev5287+g53ed2609-2020122100~focal.nightly
- OS Version: Linux 5.8.0-40-generic edgedb/edgedb#45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tailhook** [comment]
Currently it's rendered as :
```
edgedb> SELECT <duration>'1ms';
{<duration>'0:00:00.001'}
```
I'm not sure this is the most human-friendly way to do that, but it's can be round-tripped so this issue should be closed I think.
