### ISSUE TITLE
^-C in psql kills both psql and the repl

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#39]
SIGINT seems to be mishandled when running a psql subprocess from REPL.

**Comment by tailhook** [comment]
Unexpectedly fixed psql to not to die on Ctrl-C, but this seems to be a valid behavior (still not sure why psql doesn't set up signals in a way it should).

**Comment by elprans** [comment]
This is because `edgedb-cli` is the session leader from the standpoint of the tty.  psql itself handles ^-C perfectly when it's ran directly.
