### ISSUE TITLE
creating an instance with already taken name

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#396]
Currently, when an instance is created with a name that's already taken, the error message is printed after a table with instance summary info is printed:

```
~ » edgedb instance create foo --nightly --method=docker
┌──────────────────────┬──────────────────────────────────────────────────────────┐
│ Instance Name        │ foo                                                      │
│ Mode                 │ Docker                                                   │
│ Data Directory       │ <docker volume "edgedb_foo">                             │
│ Credentials Path     │ /home/yury/.config/edgedb/credentials/foo.json           │
│ Database Server Port │ 10700                                                    │
│ Default User         │ edgedb                                                   │
│ Default Database     │ edgedb                                                   │
│ EdgeDB Version       │ nightly_1-beta3-dev202107231400_cv202107231400 (nightly) │
└──────────────────────┴──────────────────────────────────────────────────────────┘
Initializing EdgeDB instance...
edgedb error: Credential file /home/yury/.config/edgedb/credentials/foo.json already exists. This may mean that instance is already initialized. You may run `--overwrite` to overwrite the instance.
```

This is super confusing. The command should check if the name is taken right at the beginning and should print the error message right away, not displaying the summary table at all.

In general, the table should be displayed only when the instance was successfully created.

**Comment by tailhook** [comment]
Well, we can move the name check specifically at the start. But the table is also for debugging. I.e. when someone reports issue with creating an instance it would report the table too, so we know how specifically instance should have been initialized.

**Comment by 1st1** [comment]
>  But the table is also for debugging. 

So are you suggesting always printing the table, even if the name is taken? IMO the error message already contains all the critical info (and you can add "Mode" to the error message if you wish).
