### ISSUE TITLE
Make ` edgedb instance status` display install method

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#397]
Add another column, "Installation"; can be set to "native" or "docker"

```
~ » edgedb instance status
┌──────┬───────┬─────────┬─────────────┐
│ Name │ Port  │ Version │   Status    │
├──────┼───────┼─────────┼─────────────┤
│ foo  │ 10700 │ 1-beta2 │ not running │
└──────┴───────┴─────────┴─────────────┘
```

While there, I think it's better to left-align text in headers of the ascii tables.

**Comment by tailhook** [comment]
> While there, I think it's better to left-align text in headers of the ascii tables.

Looks like `prettytable` crate [does not have this option](https://docs.rs/prettytable-rs/0.8.0/prettytable/format/struct.FormatBuilder.html), I can ask for it if you wish. But I don't think it's that important.

**Comment by 1st1** [comment]
> Looks like prettytable crate does not have this option

Ah, got it.

> I can ask for it if you wish.

Let's file a feature request, why not. If it's trivial to implement maybe we should PR.

> But I don't think it's that important.

Yeah, it's a minor thing, certainly.
