### ISSUE TITLE
Ctrl-C doesn't stop project init

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#398]
- EdgeDB Version: "nightly" 
- OS Version: gentoo

If I press `Ctrl-C` in the middle of `edgedb project init` after it started initializing, the process just keeps going in the background until it finishes. The status in the end appears to be `homework    │ ?    │ ?      │ inactive`, though. It would be nice if `Ctrl-C` would actually shut down the initialization.

Same behavior happens for `edgedb instance create`.

**Comment by tailhook** [comment]
Yeah, we have to do this at some point. But note, this is a huge and barely testable task.

**Comment by tailhook** [comment]
Should be working fine now. Please report if there are any issues with that.

Note: we don't "undo everything" on Ctrl+C. We just make sure that interrupt works. And make sure that `instance destroy` and `instance status/list` works even if instance is partially initialized (and on the other hand, `project unlink -D` doesn't work as we only link when instance is fully initialized).
