### ISSUE TITLE
Feature request: ability to wait until database is ready to accept connections

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb-cli#4]
Original post from spectrum: https://spectrum.chat/edgedb/general/a-way-to-wait-until-database-is-ready~0a96b827-26a1-4207-9f46-16cab8ac0068

Currently it seems like the only way to wait for edgedb is repeating requests during database bootstrapping until they succeed.
This is not the cleanest solution and is prone to errors.
My suggestion is to add `wait` subcommand for CLI tool that blocks until database is ready to accept connections.

**Comment by tailhook** [comment]
Implemented this in Rust CLI. In the form of `--wait-until-available=15s` (i.e. timeout is always explicit). We may add shorter option and/or implicit timeout later if usage of option is common enough.

**Comment by 1st1** [comment]
> Implemented this in Rust CLI. In the form of --wait-until-available=15s

This looks find to me, but we haven't really discussed this (at least I don't recall).  @elprans does this look good to you too?

**Comment by elprans** [comment]
LGTM
