### ISSUE TITLE
centered content in terminal can look broken

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#410]
- EdgeDB CLI Version: edgedb-cli 1.0.0-beta.2+d20210729.ge9b2f56d0  
- OS Version: Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
![Screenshot from 2021-07-29 13-36-45 CROPPED](https://user-images.githubusercontent.com/8278635/127567773-0eeaed2d-1554-4850-8383-d0d3bee2cf71.png)

**Comment by tailhook** [comment]
Looks like @fantix made them on the left in #419
