### ISSUE TITLE
`edgedb project init` fails on fetching EdgeDB versions

### ISSUE THREAD

**Issue by unmade** [edgedb/edgedb-cli#418]
- EdgeDB Version: N/A
- EdgeDB CLI Version: 1.0.0-beta.2
- OS Version: macOS Big Sur 11.4 (20F71) / MacBook Pro (13-inch, M1, 2020)

Steps to Reproduce:

1. git clone this project: https://github.com/unmade/shelf-back
2. run `edgedb project init`
3. when asked how you'd like to run EdgeDB select `local (docker)`

These steps result in error:

```
edgedb error: Cannot find EdgeDB version 1-beta2: failed to fetch JSON at URL: https://registry.hub.docker.com/v2/repositories/edgedb/edgedb/tags?page_size=1000
  Hint: try different installation method or remove `server-version` from `edgedb.toml` to install the latest stable
```

---

I've also tried to remove `server-version` from `edged.toml` but nothing changes.

I installed edged-cli as recommended:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh
```

**Comment by tailhook** [comment]
Sorry, this is a known problem. We should be able to release a new version shortly (this week). It you want to try earlier, you can install nightly CLI (note it's perfectly valid to use nightly CLI to install stable EdgeDB), by installing this way:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s --  --nightly
```

**Comment by unmade** [comment]
Thanks, the nightly build worked for me

**Comment by tailhook** [comment]
You can download https://packages.edgedb.com/dist/win-x86_64.nightly/edgedb-cli_latest_nightly.exe and either run it with `file.exe cli install` or save the binary as `edgedb-init.exe` and run/double-click it.

I'm not sure if it's possible to make command-line argument in ps script (I think env vars powershell aren't very convenient for one-off changes). Maybe we can have `ps1.edgedb.com/nightly`, @elprans ?
