### ISSUE TITLE
No exit command or formatting

### ISSUE THREAD

**Issue by cosmophile** [edgedb/edgedb-cli#42]
On EdgeDB 1.0-alpha.3+dev.198.g9e8c0613 I'm surprised to notice that exit and \q don't seem to work in the REPL, only ctrl+d does. Also my results are no longer nicely formatted and thus harder to read. +1 to bringing exit back and reverting to prettier results, please!

**Comment by elprans** [comment]
Are you referring to string formatting?  If so, try `\set expand-strings on`

**Comment by cosmophile** [comment]
No @elprans I mean the cli results were previously formatted in a "prettier" style format that made it easy to read nested results etc, whereas now everything is a single line. (Setting `expand-strings` or changing `/output-mode` to json doesn't seem to affect it.) Not a priority I'm sure but if it's a toggle or two away it'd be great to have that back. l love banging on the REPL and find it the best way to grok EdgeQL, so prettier results would be great.

**Comment by tailhook** [comment]
Fixed `\q`. Can you show an example that works bad with `\set expand-strings on` ?

**Comment by cosmophile** [comment]
Thanks a lot! Regarding "formatting" I'm afraid I'm not being very clear, and might possibly be wrong now that I've run a few more queries. I'll close this for now and get back to you if I have this issue again.
