### ISSUE TITLE
Ordering of options doesn't correlate to code

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#433]
Can we make the options order correlate to the structs that describe them? I.e. `--json` and `--tab-separated` are defined next to each other, but `--no-version-check` is printed between them.

```
FLAGS:
    -h, --help                Prints help information
    -j, --json                JSON output for the queries (single JSON list per query)
        --no-version-check    Disable version check
    -t, --tab-separated       Tab-separated output of the queries
    -V, --version             Show command-line tool version
```

**Comment by tailhook** [comment]
Looks like it's possible (#434), but I'm not sure it's a great idea. Most fields in the structures are quite arbitrary. It's even more the case when `flatten` is used. And default alphabetic ordering is not that bad for users, if they need to search for some option.

Mostly option grouping is explicit and more useful. Few exceptions like `--no` are a bit ugly, but I don't think that is enough justification to argue about ordering of every field.

**Comment by 1st1** [comment]
Yeah. See https://github.com/edgedb/edgedb-cli/pull/447 where I did apply the order. Other than that, top level `edgedb -h` now starts with

```
FLAGS:
    -h, --help                Prints help information
        --help-connect        Print all connection options for REPL and subcommands
    -V, --version             Show command-line tool version
        --no-version-check    Disable version check
```

and this default order looks just fine.
