### ISSUE TITLE
--project-dir option to edgedb project init eroniusly detects edgedb.toml

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#441]
The `edgedb project init --project-dir <some_existing_dir>` command seems to erroneously detect an edgedb.toml file when there is not one present. This only happens when the `--project-dir` option is used.

- EdgeDB CLI Version: EdgeDB CLI 1.0.0-beta.2+d20210805.ga3f8bd3c5
- OS Version: Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
```bash
$ mkdir -p /tmp/a/b/c
$ ll /tmp/a/b/c
total 8
drwxrwxr-x 2 fmoor fmoor 4096 Aug  5 09:45 ./
drwxrwxr-x 3 fmoor fmoor 4096 Aug  5 09:45 ../
$ edgedb project init --project-dir /tmp/a/b/c
Found `edgedb.toml` in `/tmp/a/b/c`
Initializing project...
edgedb error: error reading project config `/tmp/a/b/c/edgedb.toml`: No such file or directory (os error 2)
```

**Comment by tailhook** [comment]
Oh, `--project-dir` doesn't do any detection. It expects that . And this is supposed to be intentional. Are you confused by the `Found edgedb.toml` message?

**Comment by fmoor** [comment]
Yes the `Found edgedb.toml in /tmp/a/b/c` seems miss leading. The command output seems to say, "I found X. X doesn't exists." Which doesn't make sense and feels broken. 

Also it seems like invocations of `edgedb project init` with other options but without `--project-dir` creates an edgedb.toml if missing. If this option suppresses that behavior. It seems like it should be documented if that is intentional.
