### ISSUE TITLE
Add support for `<config-dir>/edgedbrc`

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#444]
A `<config-dir>/edgedbrc` file should be read at startup and commands within executed line by line.  Useful to pre-configure the REPL with slash commands to users' liking.

**Comment by elprans** [comment]
Implementing this should also give us proper handling of piping into bare `edgedb`, since reading `edgedbrc` is basically that, except we don't want to be showing output of commands from `edgedbrc` as these would just be noise, although showing `ran N commands from edgedbrc` is still useful, I think.

**Comment by 1st1** [comment]
Related PR https://github.com/edgedb/edgedb-cli/pull/481

**Comment by tailhook** [comment]
I think this is not relevant for now after #481. Maybe we will reconsider later.
