### ISSUE TITLE
Ctrl+C during query execution quits REPL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#45]
Edgedb version: EdgeDB 1.0-alpha.3+dev.198.g9e8c0613
REPL version: edgedb-cli 0.1.0

If you press `Ctrl+C` during the `SELECT sys::sleep(999)` query, the REPL just quits. Considering that if the query isn't running, `Ctrl+C` simply aborts query input presenting a new prompt, this is unexpected.

(Same happens to other long-running queries, not just `sleep`)

Ideally it should attempt to cancel the query, but at the very least, quitting REPL should not happen. It might be a good idea to indicate what was done, too. In old REPL, I think the line became grayed-out, like a comment. We could do that. Also something as simple as just "echoing" `Ctrl+C` instead of the query result might also help, just to give a visual indication in case colors aren't available. A message like "Query cancelled" may be appropriate, but because this scenario is subject to the same race conditions as #40 perhaps we shouldn't imply anything about the status of the query on the server.

As far as I can tell the query still runs on the server even after `Ctrl+C` closes REPL and the REPL is restarted. Try this one:

```
CREATE TYPE Foo {CREATE PROPERTY val -> str};
INSERT Foo {val := <str>datetime_current() ++ <str>sys::sleep(20)};
```

Hit `Ctrl+C` before once the query starts. Re-enter REPL and try `SELECT Foo{val}` immediately and after 20 seconds. 

@elprans is it possible to cancel the query? How many queries like that do I need to spam to severely impede the EdgeDB server (let's say I use `sleep(999)`)? What (if anything) would fail in that case?

**Comment by tailhook** [comment]
I think cancellation is still not implemented in edgedb, and is unlikely a priority. Other than that, I'm not sure it's important. It's equally nice to break from shell on Ctrl+C when something unexpectedly hangs (instead of resorting to Ctrl+/ or seeking for another way to kill the process).

There is also a number of complexities for implementing Ctrl+C in arbitrary code in rust. We can review the issue again when cancellation is implemented.

**Comment by 1st1** [comment]
No, I think this should be handled the same way as in pure Python implementation -- the connection is terminated and a new one is opened. We can make that explicit by showing a message. Once we have the cancellation API we will revisit this. But Basically Ctrl+C should never ever break the user from the repl -- that's just bad UX.

**Comment by tailhook** [comment]
> Aside from long running queries nothing should unexpectedly hang -- that would be a bug.

Well, in the real world also:
1. Connection establishment
2. Writing a file (e.g. a history)
3. Connection termination might too, but that easier to timeout.
4. Swapping (memory pressure)
5. Executing a pager

But that's not a point. Yes, we can drop connection on Ctrl+C, but there is almost no chance it can be done for Alpha 3.
