### ISSUE TITLE
REPL history commands

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#46]
Edgedb version: EdgeDB 1.0-alpha.3+dev.198.g9e8c0613
REPL version: edgedb-cli 0.1.0

The `\s` command shows the history numbered with negative offsets. However the `\e` command doesn't appear to take negative offsets and takes positive line numbers instead. Unfortunately there's no simple way of actually getting the positive index of a given command.

To be clear, I prefer negative offset counting, and it would be natural to use the same numbering for `\e` command (if we have to chose only one).

Incidentally, can we control the history length? Maybe add a `\set` command for that, too?

```
victor> \e -1
Error parsing backslash command: Found argument '-1' which wasn't expected,
or isn't valid in this context
```

It also appears that the current session history gets lost when `Ctrl+C` kills the REPL (see issue #45), resetting back to the state before the last `edgedb` command was run. This is somewhat undesirable, as the same history loss happens if the REPL is simply killed. I would think that if something caused the REPL to die, it's quite useful to *have* the command history. I mean I haven't tried rebooting or crashing the computer in some other way as a "kill" mechanism, but I'm guessing that I'd lose my history then, too.

**Comment by tailhook** [comment]
Well this stopped to work when we started to use command-line semantics for commands (since dash now means "its an optional argument"). Not sure I can easily fix that. Probably we can use positive numbers for counting backwards.

Other things here look fixable.

**Comment by tailhook** [comment]
I've managed to fix `-1`. Other things are in to do list.

**Comment by tailhook** [comment]
Looks like all three sub-issues addressed.

**Comment by 1st1** [comment]
> Probably we can use positive numbers for counting backwards.

I think we should use positive numbers, using negative ones is a bit weird. Do we need to open a new issue for that?

**Comment by tailhook** [comment]
I think we want to keep positive ones for ipython-like mode where we enumerate requests:
```
edgedb [16]> SELECT 1;
edgedb [17]> SELECT 1+1;
```

So yes, please, open a separate issue for discussion.

**Comment by 1st1** [comment]
> So yes, please, open a separate issue for discussion.

Can you open it? I'm not sure what's to discuss. I was under impression that you can't parse negative offsets.

**Comment by tailhook** [comment]
> Can you open it? I'm not sure what's to discuss. I was under impression that you can't parse negative offsets.

It turned out easy to do. So we don't have any problems with negative offsets.
