### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#476]
General look of configuration file `$XDG_CONFIG_DIR/edgedb/cli.toml`:
```
[shell]
expand-strings = true
history-size = 10000
implicit-properties = false
input-mode = "emacs"
limit = 100
output-format = "default"
print-stats = false
verbose-errors = false
```
All options are the same as in `\set` command, except types are are adjusted (`on/off` -> `true/false`).

**Comment by 1st1** [comment]
Overall I'm fine with the proposed format. We can also add something like `run = ["list", "of", "edgeql", "commands", "to", "be", "executed"]` but I guess there's no need for that right now.

> General look of configuration file $XDG_CONFIG_DIR/cli.toml:

`$XDG_CONFIG_DIR/edgedb/cli.toml`?

> All options are the same as in \set command, except types are are adjusted (on/off -> true/false).

I really don't like the "except" part. I propose we change the REPL to parse `\set expand-strings=true` and ditch on/off.

**Comment by 1st1** [comment]
Also, I'd like us to have a global `--no-color` switch at the root `edgedb` command level. How will we configure global parameters like this via the config?

Also, another idea -- it would be great to allow putting this configuration in `edgedb.toml` project file -- kinda like per-project editor config.  So maybe we should add a `config` prefix, as in `[config.shell]`, `[config.cli]`, etc.

**Comment by tailhook** [comment]
> > General look of configuration file $XDG_CONFIG_DIR/cli.toml:
> 
> `$XDG_CONFIG_DIR/edgedb/cli.toml`?
> 

Yes, fixed.

> > All options are the same as in \set command, except types are are adjusted (on/off -> true/false).
> 
> I really don't like the "except" part. I propose we change the REPL to parse `\set expand-strings=true` and ditch on/off.

I'm okay with allowing true/false. Although with on/off most of these read better (and I think we should keep them for annoying users less).

But I'm against `=` there. We parse slash commands as command-line. Equals sign `=` is used rarely in command-line outside of options (and even there is optional).

**Comment by 1st1** [comment]
> But I'm against = there. We parse slash commands as command-line. Equals sign = is used rarely in command-line outside of options (and even there is optional).

Ah, sure.

**Comment by tailhook** [comment]
> Also, I'd like us to have a global `--no-color` switch at the root `edgedb` command level. How will we configure global parameters like this via the config?
> 

Probably:
```rust
[cli]
no-color = true
[shell]
no-color = false # override in shell specifically, you you wish
```

> Also, another idea -- it would be great to allow putting this configuration in `edgedb.toml` project file -- kinda like per-project `.editorconfig`. So maybe we should add a `config` prefix, as in `[config.shell]`, `[config.cli]`, etc.

I think `[shell]` section in `edgedb.toml` is good enough. Let's just keep in mind that sections in `edgedb.toml` and `cli.toml` should be distinct.

*(I'm also scared a bit about using `run =` from `edgedb.toml`. This can be decided later, but we should keep in mind security issues with config)*

**Comment by 1st1** [comment]
> Let's just keep in mind that sections in edgedb.toml and cli.toml should be distinct.

Why not give it a prefix though? That eliminates possible conflicts and frees our minds. :) `[config.shell]` isn't that hard to type or read compared to just `[shell]`.

**Comment by tailhook** [comment]
> > Let's just keep in mind that sections in edgedb.toml and cli.toml should be distinct.
> 
> Why not give it a prefix though? That eliminates possible conflicts and frees our minds. :) `[config.shell]` isn't that hard to type or read compared to just `[shell]`.

"Flat is better than nested?" :)

I think this frees our developer's minds very insignificantly. But creates burden on our users' minds. They now have to remember that silly "config" prefix in config file? Or is it `settings` prefix in settings file? (i.e. our `\set` commands says they are settings).

**Comment by fmoor** [comment]
> it would be great to allow putting this configuration in edgedb.toml project file

```toml
# edgedb.toml

[shell]
expand-strings = true
color-theme = "Nord"
input-mode = "emacs"
```

This sounds terrible to me. `.editorconfig` `.gitconfig` etc. govern what will eventually be checked into the repo. It seems like  `[shell]` and `[cli]` govern things that:
1. will never be checked into the repo
2. are highly personal

Why is it good for this stuff to be in `edgedb.toml`?

**Comment by 1st1** [comment]
> Why is it good for this stuff to be in edgedb.toml?

For example if your project doesn't use native bindings (say your project is in .NET), and all your queries are always executing over JSON protocol. You might want to say the `[shell] output-format=json` in your `edgedb.toml`, because that's how you debug your queries and work with them in this project.

But I hear you: this might indeed be very confusing and even inconvenient to a lot of users. We shouldn't implement this feature until users come and ask or we ourselves see a real need in that.

**Comment by elprans** [comment]
What happened to the idea of simply allowing arbitrary commands in text form?  That way users wouldn't need to re-learn how to translate slash commands to config and vice versa.

**Comment by 1st1** [comment]
> What happened to the idea of simply allowing arbitrary commands in text form?

Is that really that useful? I thought about this and I can't see how putting a `SELECT` or `INSERT` can be useful in this context, so most likely users will only have there some `\set`s. In which case the `setting=value` format is pretty universal and easy to learn/discover.

**Comment by elprans** [comment]
> I thought about this and I can't see how putting a `SELECT` or `INSERT` can be useful in this context,

Configuration? `CONFIGURE SESSION SET ...`

**Comment by elprans** [comment]
> For example if your project doesn't use native bindings

Let's keep this limited to a user-local config file for now.

**Comment by tailhook** [comment]
> > I thought about this and I can't see how putting a `SELECT` or `INSERT` can be useful in this context,
> 
> Configuration? `CONFIGURE SESSION SET ...`

This is another kind of problem:
1. "rcfile" is expected to be applied at the start, but configure settings should be applied after each reconnect. Therefore should all the rcfile reapply, essentially resetting your temporary settings by hand? Or we should cut slashcommands and reapply only queries? What if queries and settings are intermingled and queries will be different depending on settings?
2. Configuring this in user-local config is unlikely be equally useful to all the projects
3. Configuring it in project's `edgedb.toml` creates one of two issues:
    a) running arbitrary queries in arbitrary databases can be a security issue (i.e. you do `edgedb -Iprod_db` and  forget that it's running from a project directory)
    b) limiting `edgedb.toml`-specified config to only a project-linked database may not be convenient if you have multiple credentials files for a project (i.e. test or staging databases), so you want configuration to be applied to these
    
So before opening this can of worms, what specific session settings would be useful here?

@1st1  this is another reason for non using `[config.shell]`. I think we should reserve `config` key for edgedb configuration.

**Comment by elprans** [comment]
Alright, you've convinced me about `rc`-style arbitrary commands in config.  Let's stash this for now.

> limit = 100

OT: should we rename this to `implicit-limit` to be in line with `implicit-properties`?

**Comment by 1st1** [comment]
> OT: should we rename this to implicit-limit to be in line with implicit-properties?

Yes, we absolutely should rename it.
