### ISSUE TITLE
Drop the \create-database command

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#52]
I don't think we need this. Typing `CREATE DATABASE foo;` is just as long.

**Comment by tailhook** [comment]
This just mirrors `edgedb create-database`. I imagine we have `edgedb create-database --initial-schema-from-file=some.edgeql`, which can't be done in edgeql as short as this.

Also, dropping arbitrary things is just confusing. Let user decide whatever they can recall first.

**Comment by tailhook** [comment]
> > Also, dropping arbitrary things is just confusing.
> 
> Well, it's not like we added this after some discussion or because it was implemented in Python REPL, right?
> 

I mean, current status quo is whatever we support as `edgedb xxx` same thing we support at `\xxx`. By "dropping" I mean making exceptions of that rule.

> > Let user decide whatever they can recall first.
> 
> Our goal is not to ship a REPL that combines all features under the belt. It's to ship a REPL that has the minimal required set of functionality to make working with EdgeDB convenient to the best of our understanding. And then we let the users to get back to us with feature requests.
> 
> We don't want to add poorly defined features now and try to remove them when the product is stable.
> 

It isn't a poorly defined feature. It's well-defined feature: consistency between command-line subcommands and backlash subcommands.

> > I imagine we have edgedb create-database --initial-schema-from-file=some.edgeql
> 
> Well, it doesn't work that way now -- it only allows to literally `CREATE DATABASE foo;`. In which case, I think it's not very useful. So I suggest to drop/hide this feature before A3 and discuss it before adding it back in A4 if we decide so.

I'm fine with hiding it from help for now. I hope we have `--initial-schema` by A4 (that partially depends on how migration works).

**Comment by tailhook** [comment]
I think this was settled with the implementation of RFC1003.
