### ISSUE TITLE
Non-English locale breaks certain behavior

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb-cli#523]
- EdgeDB Version: 1-rc1
- EdgeDB CLI Version: 1-rc2-dev
- OS Version: Debian Stretch

Steps to Reproduce:

1. Install `locales` and add a non-English locale to `/etc/locale.gen` and reconfigure `locales`.
2. Run some CLI commands that are depending on the output of a system command with the locale, like `LANG=zh_CN.UTF-8 edgedb server uninstall --all`.

**Comment by 1st1** [comment]
> breaks certain behavior

I'm just curious -- how exactly does it break it?
