### ISSUE TITLE
`edgedb dump` should accept connection args

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#54]
The Python CLI accepts connections arguments after both `edgedb` and `dump`, with latter arguments overriding the former ones, e.g. all of the below do the same:

```
edgedb -d foo dump
edgedb dump -d foo
edgedb -d bar dump -d foo
```

This behavior of CLI command line isn't random -- we had a relatively involved discussion of this behavior in Slack.

**Comment by tailhook** [comment]
Well, now, as we support `\dump`, it's harder to do. Does it make sense `\dump -d xxxx` or `\dump -H xxx`? If it does not, does it makes sense to make a precedent of different CLI syntaxes for `edgedb dump` and `\dump`? *(can't find discussion in Slack, so don't know the original argumentation)*

**Comment by 1st1** [comment]
> If it does not, does it makes sense to make a precedent of different CLI syntaxes for edgedb dump and \dump? 

I don't actually think that the syntax must be the same. I also don't think that we should expose all commands in repl -- some of those commands mimic EdgeQL and in REPL you can just type EdgeQL directly. I think commands like `\apply-schema [ESDL FILE]` and `\exec [EDGEQL FILE]` would be useful in REPL, but maybe not so much as standalone commands.

**Comment by elprans** [comment]
@tailhook What is the status on this?

**Comment by tailhook** [comment]
Nothing changed. I still have issues with conflicting arguments in few places and with slash commands working the same as CLI commands. I think Yury was expected that [RFC 1003](https://github.com/edgedb/rfcs/pull/14) would make this clear...

**Comment by 1st1** [comment]
Paul's right. Let's finalize RFC 1003 this week and if we decide to refactor the args that's will be part of next alpha.

**Comment by tailhook** [comment]
This is done, I think.
