### ISSUE TITLE
Incorrect error message running `edgedb project upgrade` on WSL

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-cli#548]
- EdgeDB Version: n/a
- EdgeDB CLI Version: 1.0.0-rc.2
- OS Version: Ubuntu 20.04 (WSL)

Running `edgedb project upgrade` ends with incorrect error mesage on WSL:
```
$ edgedb project upgrade --to-latest
...
[systemctl] Failed to connect to bus: No such file or directory
edgedb error: failed to restore "testdb": cannot start service
To undo run:
  edgedb instance revert "testdb"
```
The error states that the instance failed to restore, although it seems that the upgrade completed sucessfully (it just cannot be started automatically as a service):
```
$ edgedb instance start --foreground testdb
INFO 18450 2021-11-12T16:36:45.516 edb.server: EdgeDB server (instance-name: 'testdb', version: 1.0-rc.2+d2021111101.g4f8ba34d6.cv202111100000) is starting.
...
```
Instead I think it should show a similar message to `edgedb project init`:
```
$ edgedb project init
...
edgedb error: Bootstrapping complete, but there was an error creating the service.
You can start it manually via:
  edgedb instance start --foreground testdb
```

**Comment by tailhook** [comment]
This should have been fixed for portable package installations. Please try!
