### ISSUE TITLE
Showing error information

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#559]
Compare the following errors:
```
edgedb> select {'1', 2};
error: InvalidTypeError: set constructor has arguments of incompatible types 'std::str' and 'std::int64'
  ┌─ query:1:8
  │
1 │ select {'1', 2};
  │        ^^^^^^^^ Consider using an explicit type cast or a conversion function.

edgedb> select <datetime>'1234-11-11';
InvalidValueError: invalid input syntax for type std::datetime: '1234-11-11'
```
The rendering is a bit inconsistent, one has `error:` prefix the other does not. There's also a difference in colors. Very importantly, the second error does not render the "hint" at all, even though the field should contain the following message `Please use ISO8601 format. Example: 2010-12-27T23:59:59-07:00. Alternatively "to_datetime" function provides custom formatting options.`.

As far as I can tell, currently we only render the hint if and only if the source context is present (I've tried generating the first error, but omitting the context). Instead we should render the hint when the hint is present, regardless of whether there is source context as well.

**Comment by 1st1** [comment]
@tailhook @fantix please take a look. We should always render the hint, even if there's no source context available.

**Comment by fantix** [comment]
@tailhook with this patch:

```patch
diff --git a/src/interactive.rs b/src/interactive.rs
index 8e319e3..b313a1c 100644
--- a/src/interactive.rs
+++ b/src/interactive.rs
@@ -456,7 +456,7 @@ async fn execute_query(options: &Options, mut state: &mut repl::State,
                             source: ref error,
                             ..
                         } => {
-                            eprintln!("{:#}", error);
+                            print_query_error(error, statement, state.verbose_errors)?;
                         }
                         _ => eprintln!("{:#?}", e),
                     }
```

It could show:

```
edgedb> select <datetime>'1234-11-11';
edgedb error: InvalidValueError: invalid input syntax for type std::datetime: '1234-11-11'
  Hint: Please use ISO8601 format. Example: 2010-12-27T23:59:59-07:00 Alternatively "to_datetime" function provides custom formatting options.
```

But I'm not sure if there's any other cases that I'm missing out.

**Comment by tailhook** [comment]
If @fantix is right, it's not because of "no source context available" but because we didn't anticipate that query error will happen so late. And we only print them in query errors. Should probably format hint as part of error formatting for any error, I think (still we can't print source context for any error at any stage, that's why we have different formatting). Although we can add @fantix's patch too, in case there is more interesting stuff (like source context, or whatever) can be at this stage too.
