### ISSUE TITLE
Discuss the UX of exposing CLI commands in REPL

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#56]
This is related to #54.

We want to expose some of the useful CLI commands directly to the REPL. Dump, restore, and migrations are the first one that come to mind.

Do we want to expose ALL commands though? Should we mirror command arguments structure into the REPL?

**Comment by tailhook** [comment]
One thing I noticed for myself: I'm using `\create-database` instead of `CREATE DATABASE`. The reason is probably because we don't have completion for the latter. So `\cr<tab> name` is much faster to type than `create database name;`.
