### ISSUE TITLE
Can't upgrade docker instance to portable instance

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#575]
`instance restart` prints a suggestion to upgrade my docker instance to a portable installation, but when I try to upgrade it I get an error.

```bash
$ edgedb instance restart tryit
No instance tryit found. Looking for deprecated instances...
[docker] edgedb_tryit
Deprecated service restarted.
Please upgrade instance to portable installation
$ edgedb instance upgrade tryit
edgedb error: error reading instance info: "/home/fmoor/.local/share/edgedb/data/tryit/instance_info.json": No such file or directory (os error 2)
```

- EdgeDB Version: 1.0-rc.2+d2021111101.g4f8ba34d6.cv202111100000
- EdgeDB CLI Version: EdgeDB CLI 1.0.0-rc.2+d20211123.g786c626b8
- OS Version: ubuntu 21.04

**Comment by tailhook** [comment]
This is not what the message means. We will probably just put a link to explain how to do the "upgrade".

**Comment by tailhook** [comment]
Message is updated. Other than that we will not fix it.
