### ISSUE TITLE
REPL quits on attempting to connect to the wrong database

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#59]
- EdgeDB Version: 1.0-alpha.3+dev.223.gd5f5e87c
- EdgeDB CLI Version: 0.1.0
- OS Version: linux

Steps to Reproduce:

1. In REPL try `\c nope` (or whatever other non-existing database).

Presumably we don't want to quit REPL on an exception, but rather say that there's no such database and remain in the currently valid one. It's a bit drastic to quit REPL on what amounts to, perhaps, a typo.

**Comment by 1st1** [comment]
@tailhook Paul, is this easy to fix?

**Comment by tailhook** [comment]
No. This waits for the connection refactoring. Currently, we can't have two connections active at a moment. Closing connection and reconnecting back to the original address seems to be ugly.

**Comment by tailhook** [comment]
Fixed in #78
