### ISSUE TITLE
ClientConnectionEosError when creating migrations

### ISSUE THREAD

**Issue by jonaird** [edgedb/edgedb-cli#598]
- EdgeDB Version: RC3
- OS Version: macOS 11.6

Steps to Reproduce:
I can't for the life of me find reproducible steps but I keep getting this error very frequently when trying to create migrations. Some migrations trigger it and some don't and I can't really find the pattern of what triggers it:

```
Error applying statement: ClientConnectionEosError
Rolling back last operation...
edgedb error: ClientInconsistentError: Connection is inconsistent state. Please reconnect.
```

**Comment by tailhook** [comment]
Yes, I think it is. We probably have to improve the error message as well as add pings and fix transaction timeout.
