### ISSUE TITLE
unsupported OS on x86_64: Windows 11

### ISSUE THREAD

**Issue by forsakendaemon** [edgedb/edgedb-cli#604]
Platform: Windows 11 Home
Version: 21H2
Architecture: x86_64
Installation method: Local

Output of `edgedb server _detect`:
```
[2021-12-13T03:25:06Z WARN  edgedb::version_check] Cannot check for updates: unsupported OS on x86_64
{
  "os_type": "edgedb::server::windows::Windows",
  "os_info": {},
  "detected": {
    "package": {
      "supported": false,
      "distro_name": "Windows",
      "distro_version": "",
      "distro_supported": false,
      "version_supported": false
    },
    "docker": {
      "supported": true,
      "platform_supported": true,
      "cli": "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.EXE",
      "docker_info_worked": true
    }
  },
  "methods": {
    "Docker": {
      "cli": "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.EXE"
    }
  }
}
```

Attempted to install using Docker which also failed, but that looks like a problem in edgedb-docker so I'll likely raise an issue there.

**Comment by tailhook** [comment]
Yes, we have stopped supporting docker installation in rc3/rc4 at all, so we effectively don't have windows support for now.

We plan to do a new release with Windows/WSL2 (which is Windows Subsystem for Linux) support instead in few weeks. In the meantime you can either:
1. Run dockerized instance manually using `docker run edgedb` see https://github.com/edgedb/edgedb-docker/ for more details
2. Run edgedb server in WSL (i.e. run WSL shell, initialize with manual startup: `edgedb project init --server-start-conf=manual` or `edgedb instance create --start-conf=manual` and run `edgedb instance start --foreground` in a separate shell).
  a. If you want your app running on windows natively (not in the same WSL) also copy `~/.config/edgedb/credentials` to `c:\User\name\AppData\Roaming\edgedb\credentials`. And you can use `EDGEDB_INSTANCE=instance-name` in the environment to connect to that instance (you can't use automatic project configuration for this case, we're working on this).

**Comment by tailhook** [comment]
Should be fixed in master now. You can try by installing nightly CLI:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- --nightly
```

**Comment by tailhook** [comment]
Oh, sorry, this has to be windows version. Here is how you can run install version on windows:
```
iwr https://ps1.edgedb.com/nightly -useb | iex
```
