### ISSUE TITLE
Repl command help autocompletes into input buffer on "RIGHT"

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#63]
1. Type `\set o`.  The REPL will show an autocomplete help:

![image](https://user-images.githubusercontent.com/347119/83368122-93d18a00-a36c-11ea-9a1d-875b21739160.png)

2. Press RIGHT to accept the suggested autocomplete.  The entire help gets added to the command buffer instead of just `output-mode`:

![image](https://user-images.githubusercontent.com/347119/83368192-c8dddc80-a36c-11ea-9214-9010ff2d9cd7.png)

**Comment by tailhook** [comment]
Depends on: https://github.com/kkawakam/rustyline/issues/397
