### ISSUE TITLE
Bad CPU type in executable when using M1 without Rosetta

### ISSUE THREAD

**Issue by tiberiusferreira** [edgedb/edgedb-cli#638]
- EdgeDB Version: Latest (install issue)
- EdgeDB CLI Version: Latest (install issue)
- OS Version: MacOS 12.1 (21C52)

Steps to Reproduce:

1. Try to install using `curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh`
2. Fail with `sh: line 227: /var/folders/3h/3fm0402n2c5bs0w_py_sbh480000gn/T/tmp.eaMryKC9/edgedb: Bad CPU type in executable`

I managed to track it down to https://github.com/edgedb/edgedb-cli/blob/master/edgedb-init.sh#L181 .

I've been careful to not install Rosetta as then I could accidentally end up running x86 softwares without realizing (instead of the native ones), and I think the script _assumes_ the user either has an Intel Mac or Rosetta installed.

I realize this is not the common case today, but would be nice to be able to install without Rosetta.

**Comment by tailhook** [comment]
We currently don't support server without Rosetta. So we also don't build CLI tool (that will be unable to install the server), to avoid user confusion.

You can build the tool manually, though, if you have Rust/Cargo installed. It should be as easy as:
```
cargo install https://github.com/edgedb/edgedb-cli
```

**Comment by tiberiusferreira** [comment]
Thank you for the quick response. 

> We currently don't support server without Rosetta.

So I guess we can install the CLI but there is no way to run DB without Rosetta, not even with Docker I imagine?

**Comment by tailhook** [comment]
> 
> So I guess we can install the CLI but there is no way to run DB without Rosetta, not even with Docker I imagine?

Yes, that's right.

**Comment by tiberiusferreira** [comment]
That clears it up. Thank you.
