### ISSUE TITLE
add `edgedb project instance start` for easier use on WSL

### ISSUE THREAD

**Issue by nsidnev** [edgedb/edgedb-cli#644]
At the moment, I mostly use WSL to work on my projects. The CLI support for WSL has made working with EdgeDB very convenient, thank you!

The only thing that is a bit annoying is the need to start the EdgeDB instance linked to the project with the `edgedb instance start` command. Currently, to start instance after rebooting the computer you need to remember the exact name of the instance. It seems to me that it would be very convenient if you could start a linked EdgeDB instance with a simple `edgedb project instance start` (or something similar) command, which would itself determine which instance to use.

What do you think about that?

**Comment by elprans** [comment]
The fact that instances don't start after reboot might be a bug (or simply not implemented yet).  Ideally we should make sure that `--start-conf=auto`, which is the default, to work on WSL also.  @tailhook?

**Comment by tailhook** [comment]
It should start automatically. Although, we use `Start Menu/Programs/Startup` for that. So probably it doesn't work for remote sessions or something?

**Comment by tailhook** [comment]
Ah, sorry, I've missed the fact that you're using CLI in the WSL. We only support auto start when instance is created from Windows.

*That said, I don't think you have to switch, because those instance are not accessible from within other WSL VMs/distributions*

So yes, simplifying starting of a project instance should be doable.

**Comment by nsidnev** [comment]
> We only support auto start when instance is created from Windows.

Just out of interest, is it possible to remove this limitation in the future?

> So yes, simplifying starting of a project instance should be doable.

Awesome! I'd like to help with the implementation of this command :)

**Comment by nsidnev** [comment]
closed in favor of #739
