### ISSUE TITLE
ClientConnectionFailedError: could not resolve address `("localhost", 10700)`

### ISSUE THREAD

**Issue by studentiks** [edgedb/edgedb-cli#658]
Good day!

Gratz with release of 1.0!

Wanted to try EdgeDB and went to 'quickstart tutorial'

At step  'edgedb package init'  I got error:

edgedb error: ClientConnectionFailedError: could not resolve address `("localhost", 10700)`: failed to lookup address information: Name does not resolve

![image](https://user-images.githubusercontent.com/6019222/153547714-344df8a0-b489-4dfd-a9df-06071570b1b4.png)

What can be done to fix it? Thank you!

localhost ping is fine and edgedb-server@edgedb.service runs too

- EdgeDB Version: 1.0
- OS Version: Archlinux

BR,

Roman

**Comment by elprans** [comment]
Does this happen consistently or intermittently?  What does `host localhost` show?

**Comment by studentiks** [comment]
Problem survived reboot: 

![image](https://user-images.githubusercontent.com/6019222/153640351-78d85542-ff9b-40ac-96cf-25580180e551.png)

**Comment by elprans** [comment]
This seems like a problem with your system. `host localhost` cannot resolve it either.  Check if it's in `/etc/hosts` and that `/etc/hosts` are used by your system resolver.

**Comment by elprans** [comment]
@tailhook, any reason why we can't switch to `127.0.0.1` to make things work better in cases like this?

**Comment by tailhook** [comment]
I think used `localhost` because rustls doesn't work with IPs. But we have a workaround for that anyway, so I think we can switch to 127.0.0.1.

**Comment by studentiks** [comment]
My /etc/hosts is empty and network is generic wifi configured by NetworkManager with DNS 8.8.8.8:

![image](https://user-images.githubusercontent.com/6019222/153646177-dd10ad52-689f-4003-b7df-049fb6c667c3.png)

**Comment by studentiks** [comment]
Not quite sure if this is a bug or feature, but I adjusted NetworkManager.conf and problem got away. Thank you for clues and good luck with your project!

**Comment by GenarLoya** [comment]
> No estoy muy seguro de si se trata de un error o una característica, pero ajusté NetworkManager.conf y el problema desapareció. ¡Gracias por las pistas y buena suerte con tu proyecto!

@studentiks how do you adjust NetworkManager

**Comment by dioro** [comment]
For anyone stumbling across this, check if instance is running with `gel instance list` and if not do `gel instance start {name}`. This worked for me.

**Comment by robsimmons** [comment]
Same issue and solution as @dioro, but you're supposed to give the instance name with the -I argument, so:

```
gel instance start -I {name}
```
