### ISSUE TITLE
Change execution command

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-cli#661]
Consider changing to ⌘-Enter/Ctrl-Enter to execute queries in REPL. It's more how slack works, how to send a tweet from the web interface, etc. 

There is a possibility of clashes with shortcuts in certain shells. (If so, ideally the REPL should intercept/override that.)

**Comment by tailhook** [comment]
No we can't catch Ctrl+Enter even in the terminal. The same key code as bare Enter is sent there, at list this is how it works on linux.
