### ISSUE TITLE
Installation Error on Windows 10 - first try

### ISSUE THREAD

**Issue by malutkah** [edgedb/edgedb-cli#677]
- EdgeDB Version: 1.0
- EdgeDB CLI Version: 1.0+9ecadfc
- OS Version: 21H2 19044.1566

![image](https://user-images.githubusercontent.com/73688226/155122674-abea4552-aa10-4b34-90de-56fe265d2043.png)

I wanted to install EdgeDB on my PC, but got this error message.

Steps to Reproduce:

1. cd to a Folder of your choice
2. execute the command `edgedb project init` and wait

Can I change the installation Method somehow?
Why is it using WSL?

**Comment by tailhook** [comment]
Well, it looks like you have to do `wsl --install` before using wsl for the first time. And then it will have `--import` and similar commands that we use internally?

Can you try running `wsl --install` and report what happens later:
1. Does it ask you to reboot windows afterwards?
2. Does `edgedb project init` works after that?

We probably need to detect this condition somehow automatically. But I have to research on how it can be done.

**Comment by malutkah** [comment]
Running `wsl --install` and then rebooting worked - thanks!
