### ISSUE TITLE
Confusing UX on REPL help commands

### ISSUE THREAD

**Issue by Sikarii** [edgedb/edgedb-cli#678]
- EdgeDB Version: 1.0.0@2a0873685db135bbfdb6ac35db692d37dfca8dbf93fadadde29e85f74d5e9f70 (Docker)
- EdgeDB CLI Version: EdgeDB CLI 1.0.0+7b66089
- OS Version: Windows 10 21H2 (Build 19044.1526)

Steps to Reproduce:

1. Run `\help` and `\--help` in the REPL.
2. Observe that the above commands return different output.

The user experience from having 2 separate help commands seems bad.
Commands from both help outputs seem to work just fine, they're just split in 2 places.

Additionally `\--help` shows `edgedb> \--help  ← unknown, try: \help` in the REPL, yet it still shows the message.

<details>
    <summary>\help output</summary>

    Introspection
    (options: -v = verbose, -s = show system objects, -I = case-sensitive match)
    \d [-v] NAME             describe schema object
    \ds, \describe-schema    describe the whole schema
    \l, \list databases      list databases
    \ls [-sI] [PATTERN]      list scalar types
                             (alias: \list scalars)
    \lt [-sI] [PATTERN]      list object types
                             (alias: \list types)
    \lr [-I]                 list roles
                             (alias: \list roles)
    \lm [-I]                 list modules
                             (alias: \list modules)
    \la [-Isv] [PATTERN]     list expression aliases
                             (alias: \list aliases)
    \lc [-I] [PATTERN]       list casts
                             (alias: \list casts)
    \li [-Isv] [PATTERN]     list indexes
                             (alias: \list indexes)
    
    Operations
    \dump FILENAME           dump current database into a file
    \restore FILENAME        restore the database from file into the current one
    
    Editing
    \s, \history             show history
    \e, \edit [N]            spawn $EDITOR to edit history entry N then use the
                             output as the input
    
    Settings
    \set [OPTION [VALUE]]    show/change setting, type \set for listing
                             all available options
    
    Connection
    \c, \connect [DBNAME]    Connect to database DBNAME
    
    Help
    \?, \h, \help            Show help on backslash commands
    \set                     Show setting descriptions (without arguments)
    \q, \quit, \exit, Ctrl+D Quit REPL
</details>

<details>
    <summary>\--help output</summary>

    edgedb-cli
    
    USAGE:
        \edgedb-cli <SUBCOMMAND>
    
    FLAGS:
        -h, --help       Prints help information
        -V, --version    Prints version information
    
    SUBCOMMANDS:
        configure     Modify database configuration
        connect
        database      Database commands
        describe      Describe database schema or an object
        dump          Create a database backup
        edit
        exit
        help
        history
        last-error
        list          List matching database objects by name and type
        migrate       An alias for edgedb migration apply
        migration     Migration management subcommands
        restore       Restore a database backup from file
        set
</details>

**Comment by tailhook** [comment]
Oh, nice catch! This is an artifact that we use command-line parser for slash commands.

This is not urgent I think so I'll take a look when we have planned upgrade of `clap`. So I'm putting in the plan for 2.0. Thanks for report!
