### ISSUE TITLE
Add `EDGEDB_ADMIN_SOCKET`

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#707]
In Docker container's scripts `/edgedb-entrypoint.d` and `/edgedb-entrypoint.late.d` we want both `edgedb query` and `edgedb --admin query` work seamlessly, without any extra CLI arguments.

Neither under `1.0` semantics nor under current nightly (as of f45847d) can't serve both:
1. Under 1.0 we previuosly used `EDGEDB_HOST` to specify path to unix socket. But this only works for `--admin` (as we dropped non-admin unix socket)
2. Under nightly, we don't have environment variable to specify unix path

So to make this work we need an environment variable that works only for `--admin` mode. Other than that, it should work both (a) by specifying directory with sockets and (b) the socket itself directly.

This env will only be used in CLI (because bindings don't support admin socket). Do we have to name it `EDGEDB_CLI_ADMIN_SOCKET`? (although, we don't have precedent of `EDGEDB_CLI_` prefix).

This is intended to fix: https://github.com/edgedb/edgedb-docker/runs/5981982250

**Comment by elprans** [comment]
There is a better way to fix: https://github.com/edgedb/edgedb-docker/pull/55
