### ISSUE TITLE
Windows 11: EdgeDB fails to start on boot

### ISSUE THREAD

**Issue by OriginalEXE** [edgedb/edgedb-cli#709]
- EdgeDB Version: `0.20.7`
- EdgeDB CLI Version: `1.1.1+932d5c6`
- OS Version: Windows 11

Steps to Reproduce:

1. Install Edge DB and configure it to auto-start on boot
2. Restart

Result:
![image](https://user-images.githubusercontent.com/2056251/163434747-50686133-c081-4dfd-b6f5-50e7e306efab.png)

Not sure how I can either disable start on boot, or try to fix the issue.

`edgedb instance start cmstable` works perfectly fine when I run it manually afterwards.

**Comment by tailhook** [comment]
Oh, thanks for the report! This should be fixed by #609 after recreating the instance *(this bug is artifact from times when we handled WSL user differently)*

Not sure if we'll do some automation to fix older instances.

**Comment by OriginalEXE** [comment]
Thanks. I think automation would be nice but if not, maybe instructions on how to fix existing instances manually.

Thanks
