### ISSUE TITLE
Confiusing output for `edgedb instance start --help`

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#715]
Not sure what this means:

```
        --auto-restart    With --foreground stops server running in background. And
                          restarts the service back on exit.
```

**Comment by tailhook** [comment]
It is literally what it does:
1. stops server running in background
2. Runs server in foreground
3. restarts the service back when (2) exits.

This is kinda `docker attach` to see logs but without actually attaching. Please propose a better phrasing.

**Comment by tailhook** [comment]
I don't see too many confused users. That might mean that this function is little used, which is also fine. It was also in two stable releases, so it makes little sense to rename.
