### ISSUE TITLE
Execute query ignoring cursor position 

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb-cli#716]
Previous discussion: https://github.com/edgedb/edgedb-cli/issues/262

Not sure if it's a bug or still feature request, but I've tried all combinations on MacOS – Shift-Enter, Cmd-Enter, Option-Enter, Control-Enter and the query execution ignoring cursor position doesn't work.

On iTerm2, Cmd-Enter toggles fullscreen mode. But even after disabling it (in Settings, setting this hotkey to 'Ignore), it doesn't work either (nothing happens).

In the Warp terminal (I use it as a default now, it's too good) Cmd-Enter produces the same result as simply hitting Enter in edgedb-cli.

Is it supposed to work with Cmd-Enter? Can I provide more info to figure out what's wrong?

**Comment by tailhook** [comment]
On linux Alt+Enter works. This means, it's supposed to be Option+Enter in MacOS, right? @fantix , @1st1 do you have this issue?

**Comment by fantix** [comment]
I can reproduce the same issue as @divan described on iTerm2 (and all key combos in the default terminal on macOS just insert a new line).

**Comment by fantix** [comment]
Possible solution on macOS is to use `ESC + return` (one key after another, not at the same time).

For iTerm2, the left/right option can be reconfigured to `ESC+` in the "Profile" - "Keys" tab, then `option + return` works as expected.

**Comment by tailhook** [comment]
> Possible solution on macOS is to use `esc + return` (one key after another, not at the same time).
> 
> For iTerm2, the left/right option can be reconfigured to `ESC+` in the "Profile" - "Keys" tab, then `option + return` works as expected.

I've read this initially as an implementation proposal. But it actually works now.

----

Should the issue be closed? Do we want to put it somewhere in the documentation? Do we want to duplicate it with some hot key working out of the box? (I don't know that it should be, do Ctrl+Something work? I.e. Ctrl+Space or something?)

**Comment by 1st1** [comment]
> For iTerm2, the left/right option can be reconfigured to ESC+ in the "Profile" - "Keys" tab, then option + return works as expected.

Wow, never heard of `ESC Return`... works like magic. Fantix, maybe we document this tip in https://www.edgedb.com/docs/guides/cheatsheet/repl?

**Comment by divan** [comment]
Just tried Esc-Return in the Warp terminal and iTerm2 – it works, though feels hacky (i.e. never used this combination ever). How hard would be to support, say, Option+Enter in MacOS? Is it an issue on terminals level or REPL level?

**Comment by tailhook** [comment]
> Just tried Esc-Return in the Warp terminal and iTerm2 – it works, though feels hacky (i.e. never used this combination ever). How hard would be to support, say, Option+Enter in MacOS? Is it an issue on terminals level or REPL level?

It's issue with terminal. Technically, Alt+Enter on Linux is encoded as Esc+Enter. And if you don't enable the setting displayed on the screenshot above, no modifier key is sent to the tty, so it's impossible to detect that option key modifier is pressed.

This is my understanding. I'm not sure what "Apps can change this" does and whether it's enabled by default, though.

**Comment by divan** [comment]
Thanks for clarification @tailhook. I've looked at couple other REPL discussions on this, and seems like some people got used to shift-enter as well. (See https://github.com/JuliaLang/julia/issues/6379 for example).

Esc-Enter is a workaround, but still less then optimal (esc is to far away). Do Shift-enter or Option-enter have the same issue as Cmd/Alt-Enter in terminals?

**Comment by tailhook** [comment]
@fantix, can you check Shift+Enter on MacOS, please?

**Comment by fantix** [comment]
Looks like Shift+Enter (both left and right Shift) doesn't work on macOS with or without the patch below, on both iTerm2 and Terminal.app:

```patch
diff --git a/src/prompt.rs b/src/prompt.rs
index 4397d3e..6bd4977 100644
--- a/src/prompt.rs
+++ b/src/prompt.rs
@@ -215,7 +215,7 @@ pub fn create_editor(config: &ConfigBuilder) -> Editor<EdgeqlHelper> {
         config.clone().build());
     editor.bind_sequence(KeyEvent::new('\r', Modifiers::NONE),
         Cmd::AcceptOrInsertLine { accept_in_the_middle: false });
-    editor.bind_sequence(KeyEvent::new('\r', Modifiers::ALT), Cmd::AcceptLine);
+    editor.bind_sequence(KeyEvent::new('\r', Modifiers::SHIFT), Cmd::AcceptLine);
     load_history(&mut editor, "edgeql").map_err(|e| {
         log::warn!("Cannot load history: {:#}", e);
     }).ok();
```

Maybe I'm missing something in this patch?

**Comment by tailhook** [comment]
> Maybe I'm missing something in this patch?

I don't think you're missing something. I think this is the limitation of the tty protocol.

**Comment by tailhook** [comment]
Looks like there is nothing actionable left here.
