### ISSUE TITLE
Removal of edgedb.toml & dbschema doesn't reset project/folder

### ISSUE THREAD

**Issue by goleary** [edgedb/edgedb-cli#718]
I ran the steps laid out in the quickstart in a directory that I had previously run the quickstart in, but after deleting all files in that directly and I get this error:

`edgedb error: Project is already initialized.`

- EdgeDB Version: 1.3
- EdgeDB CLI Version: 1.1.2+f38a6e0
- OS Version: Windows 11 (running in git bash, not wsl)

Steps to Reproduce:

1. `mkdir edgedb-quickstart && cd edgedb-quickstart`
2. `edgedb project init`
3. step through interactive tool
4. delete all files/folders in `edgedb-quickstart`
5. rerun `edgedb project init`
=> `edgedb error: Project is already initialized.`

Even after deleting the entire `edgedb-quickstart` folder and recreating I still get this error.

**Comment by goleary** [comment]
after poking through the docs some more I came across [this](https://www.edgedb.com/docs/guides/projects#how-do-i-unlink-a-project) section which made it clear to me that I needed to `unlink` the directory in order to run `project init` again.

It might be nice for the cli to mention this if `edgedb project init` is run in a folder that was previously linked, but where no `edgedb.toml` file can be found.

**Comment by tailhook** [comment]
Yes, sounds good. Thanks for the report!
