### ISSUE TITLE
Respect `EDGEDB_CLIENT_TLS_SECURITY`

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-cli#720]
- EdgeDB Version: 1.3
- EdgeDB CLI Version: 1.2
- OS Version: macOS

The CLI doesn't seem to properly read the value of `EDGEDB_CLIENT_TLS_SECURITY`. By contrast `EDGEDB_CLIENT_SECURITY` (which should behave identically) is working fine.

```sh
$ EDGEDB_CLIENT_TLS_SECURITY=insecure edgedb migrate --dsn <remote-dsn>  
[2022-05-14T04:12:02Z WARN  rustls::conn] Sending fatal alert BadCertificate
edgedb error: ClientConnectionFailedError: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
$ EDGEDB_CLIENT_SECURITY=insecure_dev_mode edgedb migrate --dsn <remote-dsn>
Everything is up to date. Revision m1kt42vjynoq2uik53rdzfjp2ecbr2upzqhpdvfzyml5xztdzkwnla
```

**Comment by tailhook** [comment]
I think this is the correct behavior:
1. EDGEDB_CLIENT_SECURITY is a global parameter, so it always overrides, while
2. EDGEDB_CLIENT_TLS_SECURITY is overriden by implicit `tls_security=default` parameter in DSN (i.e. it's a part of environment variable credentials, so all of them are reset when `--dsn` is used)
