### ISSUE TITLE
Error with TLS certificate when deploying through AWS 

### ISSUE THREAD

**Issue by vonkoff** [edgedb/edgedb-cli#734]
- EdgeDB Version: EdgeDB 1.4+0b7ba44
- OS Version: Mac OS Monterey

Steps to Reproduce:

1. Follow the guidelines for deploying through AWS [found here](https://www.edgedb.com/docs/guides/deployment/aws_aurora_ecs)
2. Tried both network interfaces and got different errors
1st error:
`[2022-06-02T00:42:24Z WARN  edgedb::version_check] Newer version of edgedb tool exists 1.2.0-dev.768+c373847 (current 1.1.1-dev.760+34e619e)
Trusting unknown server certificate: SHA1:a50d96fc1090d7bf7cba95547806f602975a4ace
Password for 'edgedb': 
[2022-06-02T00:42:26Z WARN  rustls::conn] Sending fatal alert BadCertificate
edgedb error: ClientConnectionFailedError: invalid peer certificate contents: invalid peer certificate: CertNotValidForName`
2nd error:
`[2022-06-02T01:02:51Z WARN  rustls::conn] Sending fatal alert DecodeError
edgedb error: ClientConnectionFailedError: invalid peer certificate encoding
`

I'm not sure what the issue could be because certificate mentioned here is different from the one I could find in my config file for EdgeDB. That would mean that I would have to do something that wasn't stipulated in the tutorial and I'm not sure what that would be.

**Comment by vonkoff** [comment]
I followed the cloud formation instructions. 

That command worked! And I was able to apply my migrations 😊

Thanks a ton. I should probably remember to not stay on nightly once I go into production with this.
@fmoor

**Comment by elprans** [comment]
@fmoor, please file a new bug for the cert failure in nightly, so we can investigate and fix

**Comment by tailhook** [comment]
> The only caveat is that the guide doesn't mention that you might have to wait a few minutes for the RDS instances to come up before the edgedb instance link command will succeed

We may want to add `--wait-until-available=10min` to the `link` command-line?

**Comment by fmoor** [comment]
cert failure issue opened here https://github.com/edgedb/edgedb-cli/issues/738
