### ISSUE TITLE
`edgedb project init` seems stuck on `Checking EdgeDB versions...`

### ISSUE THREAD

**Issue by nicu-chiciuc** [edgedb/edgedb-cli#735]
- EdgeDB Version: <unknown yet, probably 1.4>
- EdgeDB CLI Version: EdgeDB CLI 1.1.2+58eb29e
- OS Version: Ubuntu 22.04 LTS

Steps to Reproduce:
1. Install Ubuntu 22 inside WSL2 on a windows machine
2. Install edgedb inside the wsl
3. Run `edgedb project init`, responding to the name question and the "Do you want to start instance automatically" question
4. The cli is stuck on "Checking EdgeDB versions..."

**Comment by nicu-chiciuc** [comment]
That was run on a project that already had config files. If I run `edgedb project init` in an empty directory the same thing happens after responding to the questions.

**Comment by elprans** [comment]
Does the WSL distro have outbound network access?

**Comment by nicu-chiciuc** [comment]
I think it did, I could `ping` stuff for example. I solved this issue by:
1. Building the cli locally and using it instead
2. Adding wsl to Window Defender Firewall 

I think I got after the "Checking EdgeDB versions..." after step 1.

**Comment by tailhook** [comment]
@nicu-chiciuc, adding to firewall makes a lot of sense. But from your answer I'm not sure, if there any difference between CLI built locally and installed by a script. Did it make any difference?

We can probably print a message "please add WSL to Windows Defender Firewall" if `Checking EdgeDB versions` takes a lot of time. This should include a link to the instruction. /cc @colinhacks.

**Comment by nicu-chiciuc** [comment]
I can test this with multiple versions and enabling/disabling the firewall if that would help.

**Comment by tailhook** [comment]
Current nightly shows a warning when checking version is stuck. Let's see how well this works for the new users.
