### ISSUE TITLE
No such file or directory (os error 2) when bootstrapping, portability issue

### ISSUE THREAD

**Issue by ranfdev** [edgedb/edgedb-cli#754]
- EdgeDB Version: 1.4+5ffe34b
- EdgeDB CLI Version: tested with the latest available from the website and with the latest git commit (https://github.com/edgedb/edgedb-cli/commit/3c65c8bf0a09988356ad477d0ae234182f809b0a) 
- OS Version: NixOS unstable

Steps to Reproduce:

1. cargo run instance create test

Error:
```
edgedb error: cannot bootstrap EdgeDB instance: bootstrap failed to start (command-line: "/home/lollo/.local/share/edgedb/portable/1.4/bin/edgedb-server" "--bootstrap-only" "--data-dir" "/home/lollo/.local/share/edgedb/data/.~denofreshtest_6067.tmp" "--runstate-dir" "/run/user/1001/edgedb-denofreshtest_6067" "--tls-cert-mode=generate_self_signed" "--bootstrap-command" "\n            ALTER ROLE edgedb {\n                SET password_hash := \"SCRAM-SHA-256$4096:uOjjiAbpwVpIyrG8BZE16Q==$3ZMGP4bonfHrSSszI+7ba8iVuMalITSCjp73JYuqoBQ=:YLtKimFpK4ureLxvYHIs+3Z3ucoVbX98x5bzYoVt1U0=\";\n            };\n            "): No such file or directory (os error 2)
```

I've added some anyhow's error contexts and I've traced the error back to this line:
https://github.com/edgedb/edgedb-cli/blob/3c65c8bf0a09988356ad477d0ae234182f809b0a/src/portable/create.rs#L188.

When trying to run the command manually
```
$ ~/.local/share/edgedb/portable/1.4/bin/edgedb-server
```

I get 
``` 
bash: /home/lollo/.local/share/edgedb/portable/1.4/bin/edgedb-server: No such file or directory
```

While the executable is clearly there...
```
$ ls -la ~/.local/share/edgedb/portable/1.4/bin/edgedb-server 
-rwxr-xr-x 1 lollo users 370992 May 16 22:32 /home/lollo/.local/share/edgedb/portable/1.4/bin/edgedb-server
```

I think that's a common issue on NixOS when trying to run dynamically linked binaries. 

I guess that binary isn't completely portable?

**Comment by elprans** [comment]
The binaries _are_ portable, except one bit -- the loader entry in the ELF file, which is impossible to make completely portable.   Thus, on Nix you have to `AutoPatchelfHook` (if making a package) or `patchelf` the executables to where your `ld-linux` is.  See, e.g. [1](https://nixos.wiki/wiki/Packaging/Binaries), and [2](https://gist.github.com/CMCDragonkai/1cac0299230f110a6f842ceb654fa0d0)

**Comment by ranfdev** [comment]
Indeed, that's the problem.
I've packaged edgedb-cli for nix at https://github.com/NixOS/nixpkgs/pull/179992. The package adds a patch to run `patchelf` over the downloaded binaries. 🙂
