### ISSUE TITLE
Install failed on CentOS 7.6

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb-cli#756]
Hi, just tried to install EdgeDB on the server with CentOS 7.6.1810, and got this message:

```bash
# curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh
info: downloading installer
Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure
sh: line 258: $3: unbound variable
```

https://github.com/edgedb/edgedb-cli/blob/3c65c8bf0a09988356ad477d0ae234182f809b0a/edgedb-init.sh#L258

**Comment by elprans** [comment]
Should work now.
