### ISSUE TITLE
edgedb --version does not output a newline

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#76]
The output of `edgedb --version` does not include a newline, so the output is garbled by the prompt:

```
[root@8428a91f4e1e /]# edgedb --version
edgedb-cli 1.0.0-alpha.3+g075b9784f.d20200604[root@8428a91f4e1e /]#
```

**Comment by tailhook** [comment]
Filed [a bug in clap](https://github.com/clap-rs/clap/issues/1960).
