### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#77]
The today's build seems to be broken:

```
 + cargo install --root ../../../_artifacts/tmp/edgedb-cli --path ../../../edgedb-cli --locked
  Installing edgedb-cli v1.0.0-alpha.3+gfc28c7156.d20200612 (/tmp/metapkg.8plq5vsl/edgedb-cli/edgedb-cli/_artifacts/build/edgedb-cli/../../../edgedb-cli)
    Updating crates.io index
    Updating git repository `https://github.com/clap-rs/clap`
error: failed to load source for a dependency on `clap`
```

**Comment by elprans** [comment]
This appears to be a Cargo issue on <1.44.  Upgrading to 1.44 seems to fix this.

**Comment by tailhook** [comment]
I'm not sure I can do anything about that. My github actions use latest stable. Does `edgedb-pkg` have a fixed version? Should I update docs?

Do you have link to the cargo issue?

**Comment by elprans** [comment]
This is actually due to this line in `clap`: https://github.com/clap-rs/clap/blame/055568d3fe9fd3e96366035e4129975001c7e01c/clap_up/Cargo.toml#L31

Older Cargos seem to try to eagerly resolve the dependency although `clap_up` is not referenced anywhere.  I think we can just bump Rust to 1.44 and move on.  I've already done that for `edgedb-pkg`: https://github.com/edgedb/edgedb-pkg/blob/c721f9bf047484c2c755b574e452d40d271a3e3f/integration/linux/build/update.sh#L35
