### ISSUE TITLE
Upgrades to 2.0 sometimes fail on Apple Silicon hardware with x86_64 builds

### ISSUE THREAD

**Issue by jfeiwell** [edgedb/edgedb-cli#790]
- EdgeDB Version: 1.4 trying to upgrade to 2.0
- OS Version: Monterey (M1)

Steps to Reproduce:

Pic attached of entire issue

<img width="1018" alt="Screen Shot 2022-07-28 at 2 49 26 PM" src="https://user-images.githubusercontent.com/12669260/181625077-ea56fb56-6db6-4244-951b-0686f140f854.png">

Schema:

**Comment by 1st1** [comment]
@elprans @tailhook Paul, we should automatically update the CLI to native m1 build.

**Comment by tailhook** [comment]
> @elprans @tailhook Paul, we should automatically update the CLI to native m1 build.

The hardest part here is not updating CLI to native m1 build but upgrading server to the native m1 build.

Is postgres' data directory compatible between x86 and m1 build?

**Comment by tailhook** [comment]
> > @elprans @tailhook Paul, we should automatically update the CLI to native m1 build.
> 
> The hardest part here is not updating CLI to native m1 build but upgrading server to the native m1 build.
> 

On the other hand, if CLI is updated before upgrading server it should install new version in arm64 and regular upgrade should work. So probably I was overthinking it a bit.

**Comment by elprans** [comment]
> it should install new version in arm64 and regular upgrade should work

Yes

**Comment by tailhook** [comment]
This should have been fixed.
