### ISSUE TITLE
Local instance listen on IPv6 ::1 too

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb-cli#797]
@colinhacks:

> Node 18 now resolves localhost to ::1 by default which causes connection issues because the instance doesn’t listen on ::1  by default.

Only listening on `127.0.0.1` was added in #745, and edgedb/edgedb#3899 is overwriting instance config with socket activation config, so this issue cannot be worked around with a `edgedb configure set listen_addresses 127.0.0.1 ::1`.

Ideally, the local instance could listen on `::1` too.

**Comment by Mat-moran** [comment]
I had the same problem and it works, thanks.
