### ISSUE TITLE
Irronius warning about newer CLI version

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#816]
The CLI seems to think I ought to be using a dev version instead of the stable version. I have the latest stable version of the cli installed. Some commands produce a warning that I'm not on the latest version of the cli and list the latest `dev` version as being newer. I had the dev version installed and ran `curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh` before noticing this behavior. Maybe I have managed to break my installation?

Steps to Reproduce:
```bash
$ edgedb instance list
[2022-08-12T20:50:38Z WARN  edgedb::version_check] Newer version of edgedb tool exists 2.1.0-dev.834+c5d72b2 (current 2.0.4+c7a8cb4). To upgrade run `edgedb cli upgrade`
No instances found

$ edgedb cli upgrade
Already up to date.

$ edgedb --version
EdgeDB CLI 2.0.4+c7a8cb4

```

**Comment by tailhook** [comment]
Hm, looks like we don't refresh the cache when switching channel.
