### ISSUE TITLE
Add "testing" channel

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-cli#819]
Add "testing" channel for CLI and EdgeDB server that contains `-alpha`, `-beta`, and `-rc` versions of the tools.

**Comment by tailhook** [comment]
Waiting for @elprans to do some preparation work on the repository side.

**Comment by elprans** [comment]
Testing channel is in the repos.  Server 3.0-alpha.1 as well as CLI 2.3.0-alpha.1.

**Comment by tailhook** [comment]
Added in #901
