### ISSUE TITLE
Cannot upgrade EdgeDB CLI

### ISSUE THREAD

**Issue by avedetvedea** [edgedb/edgedb-cli#831]
- EdgeDB CLI Version: EdgeDB CLI 2.0.4+a7fc49b
- OS Version: MacOS 12.1

Steps to Reproduce:

1. EdgeDB CLI states **Newer version of edgedb tool exists 2.0.5+79cc3e1 (current 2.0.4+a7fc49b)**
2. run edgedb cli upgrade --verbose
3. EdgeDB CLI states **Only binary installed at "/Users/ata/Library/Application Support/edgedb/bin/edgedb" can be upgraded**

**Comment by colinhacks** [comment]
If you installed the CLI through Homebrew (or another method) initially, you'll have to use Homebrew to upgrade. The `edgedb cli upgrade` command only works if you installed initially using the recommended shell script approach (`curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh`). You can run `which edgedb` to see where the binary is currently installed.

**Comment by avedetvedea** [comment]
which edgedb `returns /usr/local/bin/edgedb`, so what does this imply?

**Comment by avedetvedea** [comment]
So I updated it with the brew. I couldn't find the brew package name so directly ran `brew upgrade`. This is not an issue/bug then, closing, thank you.
