### ISSUE TITLE
Intermittent failures on dump Restore

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#84]
`test_dump_fuzz_01` is failing itermittently with `Error: future has timed out`, see https://github.com/edgedb/edgedb/runs/851774571?check_suite_focus=true#step:12:3500 for an example

**Comment by elprans** [comment]
This bit is suspicious:

```rust
    // This future should be canceled by wait_response() receiving
    // CommandComplete
    let start_waiting = Instant::now();
    loop {
        timeout(Duration::from_secs(60), pending()).await?;
        if verbose {
            eprintln!("Waiting for complete {:?}", start_waiting.elapsed());
        }
    }
```

I don't think this is coded correctly. The `timeout` would basically return an error if the dump wasn't restored in 60 seconds.

That said, the test dump gets restored in well under 60 seconds, but the Rust side is somehow not seeing the `CommandComplete` message.

**Comment by 1st1** [comment]
> would basically return an error if the dump wasn't restored in 60 seconds.

But we shouldn't have this timeout in the first place. A restore can take minutes or potentially hours.

**Comment by elprans** [comment]
This is definitely a client bug, the server is sending `CommandComplete`, the the client `Acks` it, but then sits for the rest of the minute until the timeout:

![image](https://user-images.githubusercontent.com/347119/86983123-d478ac00-c13f-11ea-94da-60a1b997f0ad.png)

**Comment by tailhook** [comment]
This timeout shoudn't error out, just print a message, and loop indefinitely. But let me investigate.

**Comment by tailhook** [comment]
Yes. Sorry, I've misunderstood timeouts in async_std.

**Comment by elprans** [comment]
It's still a little suspicious that it sat there until the timeout and well _after_ `CommandComplete` was sent.  Shouldn't the following piece have cancelled the timeout loop?

```rust
    let result = send_blocks(&mut seq.writer, &mut input,
                             filename.as_ref(), verbose)
        .race(wait_response(&mut seq.reader, start_headers, verbose))
        .await;
```

**Comment by tailhook** [comment]
Sure this the whole point. And given that it fails only sporadically and only on CI, I assume that it only failed when timeout has hit (i.e. when `CommandComplete` took more than a minute). Do you have another observation?

**Comment by elprans** [comment]
Yes, I have observed a delay between `CommandComplete` being sent and the timeout: see the screenshot above and note the delay between 17331 (`CommandComplete` packet sent by the server) and 17626, which is where the client raises an exception and sends `Sync`.
