### ISSUE TITLE
redundant user prompts for connection options specified in --dsn

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#844]
- EdgeDB CLI Version: `EdgeDB CLI 2.1.0`
- OS Version: Ubuntu 22.04

Even if all relevant information is provided in the `--dsn` option the CLI still prompts for all these values.
```bash
$ edgedb instance link --dsn edgedb://edgedb:password@143.198.70.5:5656
Specify the host of the server [default: 143.198.70.5]:
> 143.198.70.5
Specify the port of the server [default: 5656]:
> 5656
Specify the database user [default: edgedb]:
> edgedb
Specify the database name [default: edgedb]:
> edgedb
```

It seems like it should just try to connect instead of asking again.

**Comment by tailhook** [comment]
Looks like it's not the case since #969
