### ISSUE TITLE
macOS: failed `_create_service` leaves service plist behind

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#845]
If `_create_service` fails on `launchctl bootstrap` for whatever reason, the `plist` will not be removed causing trouble when an instance with the same name is made.

**Comment by 1st1** [comment]
Need check if the service already exists and bootout it. Paul can you take a look tomorrow?

**Comment by tailhook** [comment]
> If `_create_service` fails on `launchctl bootstrap` for whatever reason, the `plist` will not be removed causing trouble when an instance with the same name is made.

We do that in `create_service`: https://github.com/edgedb/edgedb-cli/blob/32c4b20/src/portable/macos.rs#L42-L49

First I thought we should do that on `instance start`, but then I've realized that `start` should be no-op when instance is already runnning, but boot out would mean `start` == `restart`.

**Comment by tailhook** [comment]
Ah, okay, we probably check for "not loaded" service in the wrong way.
