### ISSUE TITLE
Insert `using future nonrecursive_access_policies` by default into new project schemas

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#866]
https://github.com/edgedb/edgedb/pull/4574 is adding a 'future' system to opt into behavior changes, and adding a new nonrecursive_access_policies to fix the behavior of access policies.

We would like to make it a "soft default" in 2.6. This means that when `edgedb project init` creates a new project (for 2.6 or later), we ought to automatically insert `using future nonrecursive_access_policies` into the starting empty schema file (along with a link to documentation we'll writing, probably).
This also requires generating an initial migration file that does a `CREATE FUTURE nonrecursive_access_policies`

**Comment by tailhook** [comment]
> This also requires generating an initial migration file that does a `CREATE FUTURE nonrecursive_access_policies`

As far as I can see this is done by the server.
