### ISSUE TITLE
EdgeDB cloud instance creation reports wrong instance name to connect to

### ISSUE THREAD

**Issue by zackelan** [edgedb/edgedb-cli#868]
- EdgeDB Version: 3.0-dev.7018+c2a80cd
- EdgeDB CLI Version: master branch as of 2022-11-01 (`303ae71462463fa644893ed6ced03f6da3fa25ee`)
- OS Version: NixOS 22.05.3767.6107f97012a

Steps to Reproduce:

- run EdgeDB Cloud locally using Nebula
- `edgedb cloud login`
- `edgedb instance create zackelan/test`

It succeeds, and I get:

```
Waiting for EdgeDB Cloud instance creation...        
EdgeDB Cloud instance zackelan/test is up and running.
To connect to the instance run:                                                                           
  edgedb -I test
```

That command fails to connect. If I run `edgedb instance list` I can see that it expects me to use `zackelan/test`.

```
$ edgedb instance list
┌────────┬───────────────┬────────────────────────────────────┬─────────────┬───────────┐
│ Kind   │ Name          │ Port                               │ Version     │ Status    │
├────────┼───────────────┼────────────────────────────────────┼─────────────┼───────────┤
│ remote │ edge25        │ localhost:15656                    │ 2.5+1965887 │ up        │
│ cloud  │ zackelan/test │ nomad-node2.local-1.internal:27703 │ ?           │ available │
└────────┴───────────────┴────────────────────────────────────┴─────────────┴───────────┘
```

Using the fully-qualified instance name allows me to connect. The CLI should tell me to use that instead.

**Comment by fantix** [comment]
Fixed in #870
