### ISSUE TITLE
`edgedb migration log --from-db` not working on 2.1.0

### ISSUE THREAD

**Issue by NextFire** [edgedb/edgedb-cli#874]
- EdgeDB Version: 2.5+1965887
- EdgeDB CLI Version: 2.1.0+e136de4
- OS Version: Debian GNU/Linux 11 (bullseye) (`python:3.10` Docker image)

Steps to Reproduce:

1. Upgrade EdgeDB CLI from 2.0.5+f78cf34 to latest with `edgedb cli upgrade`
2. `export EDGEDB_DSN=<...>`
3. `edgedb migration log --from-db` exits with `edgedb error: DescriptorMismatch: unexpected field id, expected name`

**Comment by jparise** [comment]
I also see this on a fresh installation of 2.6+e323277 when I get to the "[Run a migration" step](https://www.edgedb.com/docs/intro/quickstart#initialize-a-project) of the quickstart guide.

**Comment by nprbst** [comment]
@jparise `curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- --nightly` got me unstuck...
