### ISSUE TITLE
cmd: edgedb list types 

### ISSUE THREAD

**Issue by Alteian** [edgedb/edgedb-cli#883]
- EdgeDB Version: 2.6+ba1661b 
- CLI: EdgeDB CLI 2.1.0+e136de4

Just went through quickstart and during list types command I've got error:

`DescriptorMismatch: unexpected field id, expected name`

**Comment by Sikarii** [comment]
This seems to be an issue in version `2.1.0+e136de4`, the previous version `2.0.5+da7c868` works just fine.

**Comment by tailhook** [comment]
It's fixed in nightly too. We should probably do a new release.

**Comment by msullivan** [comment]
Can we cut a release tomorrow?

**Comment by Alteian** [comment]
Fixed with new release.
