### ISSUE TITLE
project init with new cloud instance

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#915]
- EdgeDB CLI Version: EdgeDB CLI 2.3.0-dev.902+e29ccdb
- OS Version: ubuntu 22.04

If I init a project and use a cloud instance name that doesn't exist then I get a resource not found error. I would expect this to create a new cloud instance instead of failing or if that is not a valid option perhaps an error explaining the correct procedure for creating a new cloud instance before initializing a project.

```bash
$ edgedb project init
Found `edgedb.toml` in /home/fmoor/src/sample2
Initializing project...

Specify the name of EdgeDB instance to use with this project [default: sample2]:
> fmoor/sample2

edgedb error: Failed to create authentication session: Resource not found.
```

**Comment by fantix** [comment]
Fixed in [21c3414](https://github.com/edgedb/edgedb-cli/pull/924/commits/21c3414e3fc102ec74bdc88f9f8656c7c1db3cde)
