### ISSUE TITLE
--server-install-method is missing from the cli

### ISSUE THREAD

**Issue by legezam** [edgedb/edgedb-cli#927]
- EdgeDB Version:

N/A since i am not able to get there

- EdgeDB CLI Version:

```
➜  edgedbinittest edgedb --version
EdgeDB CLI 2.2.6+b869667
```

- OS Version:

```
➜  edgedbinittest cat /etc/fedora-release 
Fedora release 37 (Thirty Seven)
```

Steps to Reproduce:

1. `edgedb project init --server-install-method docker` or
2. `edgedb project init --server-install-method=docker`

Getting this error:

```
➜  edgedbinittest edgedb project init --server-install-method docker
error: Found argument '--server-install-method' which wasn't expected, or isn't valid in this context

	Did you mean '--server-instance'?

	If you tried to supply `--server-install-method` as a value rather than a flag, use `-- --server-install-method`

USAGE:
    edgedb project init --server-instance <server_instance>

For more information try --help

```

According to the docs, this switch should be available: https://www.edgedb.com/docs/cli/edgedb_project/edgedb_project_init#ref-cli-edgedb-project-init

**Comment by tailhook** [comment]
Ah, sorry, that page is outdated. We don't support installation methods for quite a while. Fixed in edgedb/edgedb#4927.
