### ISSUE TITLE
tokio CLI sometimes displays new prompt before output

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#933]
```
edgedb> insert Thing { name := 'Alice2' };
edgedb> [{"id": "427806d0-a748-11ed-9f6f-ff8e23ce8888"}]
```

**Comment by msullivan** [comment]
This seems to still be happening:
```
triggers> update InsertTest filter .name = 'foo' set { name := "x" };
triggers> []
```

I had stopped seeing it, but I realize now that it was because I had pinned the CLI back before tokio.

I did some quick googling and it looks like the root cause is https://github.com/tokio-rs/tokio/issues/4347
`stdout()` produces a *new* handle to stdout. So calling `stdout().flush().await?` makes a new handle and flushes that, which doesn't help any. There is an issue open and a PR from ages to change this but they didn't seem to get it working?

**Comment by tailhook** [comment]
You're right. Thanks!
