### ISSUE TITLE
add a browser config option in edgetb.toml

### ISSUE THREAD

**Issue by Jarrodsz** [edgedb/edgedb-cli#941]
I would like to request a minimal but essential DX improvement feature.

Adding a browser flag in edgedb.toml.

Currently the default browser is used and for me on OSX that is Safari,
The edgedb UI is broken there so I keep coping the edgedb ui url from my terminal to chrome.
OR
if safari no longer breaks the UI this could be obsolute.

The problem is sometimes i wipe my instance and have to get a new url for the ui, I  do bookmark it.

It would be great if one could just set the name of the browser or the path in edgedb.toml so it would always enforce a specific browser.

Another case for this is, im using safari to browse docs and chrome to develop.
A seperation in browsers gives more focus and chrome offers some debugger options not in safari.

**Comment by 1st1** [comment]
>  The edgedb UI is broken there so I keep coping the edgedb ui url from my terminal to chrome.

I just tested Safari and everything looks OK for me. Can you document what's exactly broken for you? Screenshot or video + a screenshot of the Safari dev tools console would be helpful.

**Comment by tailhook** [comment]
Perhaps Safari support is fixed. If it's not please open an issue in the [edgedb-ui](https://github.com/edgedb/edgedb-ui) repository. I think we are more inclined to fix Safari issues than to do ad-hoc overrides of the default system browser just for this use case.

**Comment by tailhook** [comment]
Closing in favor of https://github.com/edgedb/edgedb-ui/issues/188
