### ISSUE TITLE
Installer version errors or unexpected behavior

### ISSUE THREAD

**Issue by vjjft** [edgedb/edgedb-cli#945]
When running the edgedb cli installer with the `--version` option, an error results. I expected information about the version of the cli that would be installed.

(I encountered this while attempting to determine and select which version of the cli would be installed, as I had begun encountering some errors after upgrading from `2.2.6` to `2.3.0`, and wanted to determine if those errors were version related or otherwise.)

To reproduce:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com > edgedb-cli-installer
chmod u+x edgedb-cli-installer
./edgedb-cli-installer --help
```
  <details><summary>Output includes: <code>--version    Print version information`</code></summary>
  <p>

```
edgedb-init
The installer for edgedb command-line tools

USAGE:
    edgedb-init [FLAGS] [OPTIONS]

FLAGS:
    -h, --help              Print help information
        --nightly           Install nightly version of command-line tools
    -y                      Disable confirmation prompt
        --no-modify-path    Do not configure the PATH environment variable
    -q, --quiet             Disable progress output
    -v, --verbose           Enable verbose output
    -V, --version           Print version information
```
</p>
</details>

`./edgedb-cli-installer --version`

<details><summary>Output includes: <code>error: Found argument '--version' which wasn't expected, or isn't valid in this context</code></summary><p>

```
info: downloading installer
error: Found argument '--version' which wasn't expected, or isn't valid in this context

	Did you mean '--verbose'?

	If you tried to supply `--version` as a value rather than a flag, use `-- --version`

USAGE:
    edgedb _self_install --verbose

For more information try --help
```
</p></details>

[^1]

[^1]:OS Version: macOS 13.0.1 (22A400)

**Comment by tailhook** [comment]
Well, I think it was mistakenly copied from somewhere (probably early `cli install` command). So it's historical incident (fixing by #946)

To get version info script has to fetch some repository info, parse it, etc. Which isn't easy to do in shell script. And we don't script to become very complex.

We can probably improve `cli upgrade` command to include some version information, though. Feel free to open a new issue for that.
