### ISSUE TITLE
Can't drop database with dash in the name

### ISSUE THREAD

**Issue by bayssmekanique** [edgedb/edgedb-cli#963]
- EdgeDB Version: 2.12+5454e58
- EdgeDB CLI Version: 2.3.1+ef99779
- OS Version: Windows 11 (22H2)

Steps to Reproduce:

1. Create a database including a dash in the name (ex: `test-db`).
2. Attempt to drop the database using a query and the result will fail because of the included dash.

Error:
```sh
edgedb query "drop database test-1234"
error: EdgeQLSyntaxError: Unexpected '-'
  ┌─ query:1:19
  │
1 │ drop database test-1234
  │                   ^ error
```

Additional:
Attempts to resolve by escaping the dash did not resolve the issue.

```sh
edgedb query "drop database 'test-1234'"       
error: EdgeQLSyntaxError: Unexpected "'test-1234'"
  ┌─ query:1:15
  │
1 │ drop database 'test-1234'
  │               ^^^^^^^^^^^ error
  
edgedb query 'drop database "test-1234"' 
error: EdgeQLSyntaxError: Unexpected '-'
  ┌─ query:1:19
  │
1 │ drop database test-1234
  │                   ^ error

edgedb query 'drop database "test\-1234"'
error: EdgeQLSyntaxError: unexpected character '\\'
  ┌─ query:1:19
  │
1 │ drop database test\-1234
  │      
```

**Comment by elprans** [comment]
Use backticks to quote names with special characters:

```
edgedb query "drop database `test-1234`"
```

**Comment by bayssmekanique** [comment]
So, I had tried that as well but it doesn't want to close the line. I'm sure this likely an OS level issue.
```sh
edgedb query "drop database `test-1234`"
>> ;
>> 
>> ^C
```

I was able to do it by actually entering the REPL and submitting the query that way.
```sh
edgedb      
EdgeDB 2.12+5454e58 (repl 2.3.1+ef99779)
Type \help for help, \quit to quit.
edgedb> drop database `test-1234`
....... ;
OK: DROP DATABASE
edgedb> \quit
```

**Comment by bayssmekanique** [comment]
A bit odd, but this was ultimately the single line solution using the CLI.
```sh
edgedb query 'drop database `test-1234`'
OK: DROP DATABASE
~\Dev\bayssmekanique\florida-man-super-card [feat/edgedb ≡]
```
Using backticks to escape the nested string and single quotes for the top level string.¯\_(ツ)_/¯

**Comment by tailhook** [comment]
> Using backticks to escape the nested string and single quotes for the top level string.

Yes this is how shell works. Backticks in double quotes are evaluated as a shell command and the output of that shell command is inserted into the quotes. Whereas shell doesn't do any expansion in single quotes.
