### ISSUE TITLE
Tool for squashing migration history for problematic upgrades

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#976]
We're going to need a tool that uses migration rewrites to squash the migration history, in order to enable recovering from upgrades that make it impossible the apply the existing migrations to a fresh database.

The upgrade workflow I'm picturing is something like:
1. Try running the new version in your dev environment, applying all the migrations
2. If something breaks, fix it. Use rewrites to squash the migration history.
3. Once you can create a new dev database, test out dump/restore
4. Maybe do a backup dump to be safe?
5. Deploy any changes and migration squashes to prod
6. Prod dump
7. Upgrade prod version
8. Prod restore

**Comment by tailhook** [comment]
Discussion of the specific commands:
https://github.com/edgedb/edgedb/discussions/5193
