### ISSUE TITLE
Preserve the order object name/value pairs in json output

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-cli#977]
```
edgedb> \set output-format default
edgedb> select { b := 1, a := 2 };
{{b: 1, a: 2}}
edgedb> \set output-format json
edgedb> select { b := 1, a := 2 };
[{"a": 2, "b": 1}]
```
We preserve the order of elements inside objects in default mode, but not in json mode.

While the JSON spec does say that an object is an unordered set, there *is* an order in the encoding, and the compiler should always produce SQL that produces JSON that preserves the order of shape elements in objects.

I think it would be nice if we preserved that when pretty printing the json.

This might be a pain, though.

One option would be to use a different library like: https://lib.rs/crates/strason, which does exactly the right thing here but hasn't been updated in a while so might not work? This one stores numbers as strings, too, which would fix the loss of precision currently seen when handling bigints.

We could also copy  `serde_json`'s value type and tweak it to use an `indexmap`?

**Comment by tailhook** [comment]
`serde_json` has a compile time options for that. This perhaps enables extra overhead everywhere, but I don't think this is a problem for the CLI specifically.
